insufficiently-caffeinated/caffeine

.clang-format, .gitignore, CMakeLists.txt, src/CMakeLists.txt
Just basic setup. I will start adding code in a separate PR.
=> Setup dotfiles and cmakefiles

include/caffeine/Support/Assert.h, src/Support/Assert.cpp
These are mostly just the same as we had in decaf but they've been renamed from `DECAF_` to `CAFFEINE_`
=> Add assertion macros

.github/workflows/build-project.yml, vcpkg.json
This adds a simple github action that uses the existing docker image to build + test everything.
=> Add vcpkg.json and build-project github action

CMakeLists.txt, test/CMakeLists.txt, test/unit/CMakeLists.txt, test/unit/main.cpp
No tests at the moment but when they get added they can now be run automatically.
=> Setup unit test runner

Dockerfile
=> Add dockerfile from decaf

.github/workflows/build-project.yml, include/caffeine/IR/Operation.inl, include/caffeine/IR/Type.inl, src/CMakeLists.txt, src/IR/Operation.cpp
There was some stuff that didn't get caught because none of the files were actually being linked into the test executable:
- Some of the methods with header implementations weren't marked as inline
- I missed implementing `UnaryOp::Create`
- The cmake config wasn't linking in libcaffeine when building the unit tests
- Also, the github workflow wasn't actually running any tests
This PR should fix all of those.
=> Fix minor issues from #6

README.md
Copy and pasted the README from the previous repo. Lmk if we need any changes
=> README: copy & paste

.github/workflows/clang-format.yml, CMakeLists.txt, include/caffeine/IR/Operation.h, include/caffeine/Support/Assert.h, src/IR/Type.cpp, test/unit/main.cpp
This PR adds the format cmake target and the github workflow for linting
=> Add formatter & run format

include/caffeine/Interpreter/Context.h, include/caffeine/Interpreter/Executor.h, include/caffeine/Interpreter/Interpreter.h, include/caffeine/Interpreter/StackFrame.h
Addresses #7 
This PR creates headers for the interpreter
=> Begin interpreter design

include/caffeine/Interpreter/Context.h, include/caffeine/Interpreter/Interpreter.h, include/caffeine/Interpreter/StackFrame.h, src/Interpreter/Context.cpp, src/Interpreter/Interpreter.cpp, src/Interpreter/StackFrame.cpp
This PR adds StackFrame and some other interpreter components
=> Add initial interpreter implementation

include/caffeine/Interpreter/Context.h, include/caffeine/Interpreter/Interpreter.h, include/caffeine/Interpreter/StackFrame.h, src/Interpreter/Context.cpp, src/Interpreter/Interpreter.cpp
This PR adds the visitAdd operation, and some work on the StackFrame and Context
=> Add visitAdd impl

.github/workflows/clang-format.yml, CMakeLists.txt, cmake/formatting.cmake, include/caffeine/Interpreter/Context.h, include/caffeine/Interpreter/Interpreter.h, src/Interpreter/Context.cpp, src/Interpreter/Interpreter.cpp, src/Interpreter/StackFrame.cpp
Continuing with the work in #25. This uses the check-format target in CI.
=> Rewrite check-format target

include/caffeine/Interpreter/Interpreter.h, src/Interpreter/Interpreter.cpp
This PR implements PHI nodes and branching in a similar way to decaf
=> Add Phi node and branch implementation

include/caffeine/ADT/SlotMap.h, test/unit/ADT/SlotMap.cpp
See the doc comment for slotmap for an explanation of what this does and the comment within for an explanation of how it's implemented. I've included some tests that should cover most of the general use, although they might not cover all of the edge cases.
This is needed as part of the memory system.
=> [Memory 1/N] Create slot_map data structure

include/caffeine/Support/Assert.h
As described in title. Not much else here.
=> [Memory 2/N] Allow CAFFEINE_UNREACHABLE/UNIMPLEMENTED to have custom messages

include/caffeine/Solver/Z3Solver.h, src/Solver/Z3Solver.cpp
This is a WIP PR to see whether this is on the right track
=> Add z3 solver struture

include/caffeine/IR/Operation.inl, include/caffeine/IR/Visitor.inl, include/caffeine/Interpreter/Interpreter.h, interface/caffeine.h, src/IR/Visitor.cpp, src/Interpreter/Context.cpp, src/Interpreter/Interpreter.cpp, src/Solver/Z3Solver.cpp, src/bin/caffeine.cpp, test/CMakeLists.txt, test/run-fail/CMakeLists.txt, test/run-fail/caffeine.h, test/run-pass/CMakeLists.txt, test/run-pass/branch-false.c, test/run-pass/branch-true.c, test/run-pass/caffeine.h
Fixes shit until the tests pass
=> Setup test infrastructure

.github/workflows/build-project.yml, Dockerfile, test/CMakeLists.txt
=> Ensure clang is properly detected in CI

include/caffeine/Solver/Z3Solver.h, src/CMakeLists.txt, src/Memory/MemHeap.cpp, src/Solver/Z3Solver.cpp, src/Solver/Z3Solver.h, test/unit/CMakeLists.txt, test/unit/Memory/MemHeap.cpp
This is the set of changes needed to get memory allocation code working. I'm not sure if it's completely correct at this point but it's more correct than it was when I started this.
As a bonus this makes `run-fail/sdiv-udiv-inequal.c` about 20 times faster!
=> Start getting memory code tested

src/Interpreter/Context.cpp, test/run-fail/CMakeLists.txt, test/run-fail/caffeine.h, test/run-pass/CMakeLists.txt, test/run-pass/caffeine.h, test/run-pass/fp/2plus2is4.c
As in title. Most of this change is actually modifications to the build systems to allow tests to be in subfolders
=> Allow floating point input parameters

include/caffeine/IR/Type.h, src/IR/Type.cpp
I found that I wanted this while doing some debugging. Doesn't work for all types just yet but it does work for the ones that we care about most of the time.
=> Make Type printable

include/caffeine/ADT/Ref.h, include/caffeine/IR/Operation.h, include/caffeine/IR/Operation.inl, src/IR/Operation.cpp
I got fed up with trying to figure out all the needed moving parts to add new internal state to operation and decided to simplify the whole thing somewhat.
=> Simplify Operation internals

include/caffeine/IR/Operation.h, src/IR/Operation.cpp
I found this rather useful for debugging bugs in my vector implementation.
=> Add operator<< implementation for operation

include/caffeine/IR/Value.h, src/IR/Value.cpp
This simplifies the `Value` internals by replacing a manual union with a variant and then rewriting the implementation to work with that.
I've also taken the opportunity to remove redundant assertions now that the arithmetic methods have switched to using the proper accessors. (e.g. `apint()` already asserts on `is_int()`, there's no need to repeat that within the body of `add`)
=> Simplify Value implementation

include/caffeine/ADT/SharedArray.h, include/caffeine/ADT/SlotMap.h, src/ADT/SharedArray.cpp
As part of the implementation I also needed an iterator implementation. This is a precursor to the memory support that will be added in the next couple PRs.
=> Implement hashing for SharedArray

test/run-fail/sample.c, test/run-fail/sdiv-udiv-inequal.c, test/run-pass/sdiv-udiv-equal-nonnegative.c
=> Fix compilation warnings within test files

include/caffeine/Interpreter/Interpreter.h, src/Interpreter/Interpreter.cpp, src/Memory/MemHeap.cpp, src/Solver/Solver.cpp, src/Solver/Z3Solver.cpp, src/Solver/Z3Solver.h, test/run-fail/mem/select-array.c, test/run-pass/mem/global-array-select.c, test/run-pass/mem/store-to-global.c
As in title. Also had to fix `MemHeap::write` but everything seems to work now.
Closes #108.
=> Implement store instruction

include/caffeine/IR/Assertion.h, src/IR/Assertion.cpp
As in title. I found that I needed this while debugging.
=> Add stream operator for Assertion

include/caffeine/IR/Operation.h, src/IR/Operation.cpp, src/IR/Operation.h, src/Interpreter/CtxConstEval.cpp, test/run-pass/const-folding/float.ll, test/run-pass/const-folding/int.ll
This PR is 1/2 for implementing constant folding for floating point expressions.
Part of #96
=> Add const folding for float add and sub

include/caffeine/Memory/MemHeap.h, src/Interpreter/Interpreter.cpp, src/Memory/MemHeap.cpp, test/run-pass/mem/vector-load-store.c
As in title. Implemented new read/write overloads on MemHeap to support everything.
The added test case is currently quite slow. I'm hoping some near-future optimizations will speed it up.
Closes #138.
Closes #139.
=> Implement vector load and store

include/caffeine/IR/Assertion.h, src/IR/Assertion.cpp
=> Add helper method for finding constant-value assertions

src/IR/Type.cpp
This PR fixes a compiler warning
=> Add missing case statement

CMakeLists.txt, cmake/CaffeineLinking.cmake, src/CMakeLists.txt, test/CMakeLists.txt
As in title.
Depends on #190 so leaving draft for now.
=> Implement support for LTO and custom linkers

src/Interpreter/Value.cpp, vcpkg.json
This just fixes some small things that I found when attempting to compile with MSVC. It does not make compilation work yet.
=> Fix small issues encountered when compiling with MSVC

include/caffeine/IR/Operation.h, include/caffeine/IR/Operation.inl, include/caffeine/IR/Visitor.h, include/caffeine/IR/Visitor.inl, src/IR/Operation.cpp, src/Interpreter/PrintingFailureLogger.cpp, src/Solver/Solver.cpp, src/Solver/Z3Solver.cpp, src/Solver/Z3Solver.h
This PR implements a new `ConstantArray` operation that stands for a symbolic array and then makes the required changes to support it everywhere.
=> Implement ConstantArray operation

Dockerfile, README.md
=> Add pkg-config to dependencies and update README

include/caffeine/Serialization/ValueIdMap.h, src/CMakeLists.txt, src/Protos/operation.capnp, src/Serialization/ValueIdMap.cpp, test/unit/CMakeLists.txt, test/unit/Serialization/Trivial.cpp
This is a small PR to demonstrate how Capnp works (and that we're linking with it properly etc.)
=> Add simple test to show usage for Capnp

include/caffeine/IR/Matching.h
This PR adds a matcher for ICmp operations. It also fixes an issue with `CaptureMatcher`.
This PR was pulled out of #215.
=> Implement ICmp matcher

src/IR/Operation.h
As in title. Noticed we didn't have it - decided to add it.
=> Implement constant folding for the FIsNaN opcode

include/caffeine/Interpreter/ExprEval.h, include/caffeine/Interpreter/Interpreter.h, src/Interpreter/ExprEval.cpp, src/Interpreter/Interpreter.cpp
=> [12/N] Interpreter redesign - Implement icmp opcode using ExprEvaluator

include/caffeine/Memory/MemHeap.h, src/Memory/MemHeap.cpp
=> Rewrite Allocation::write to return an LLVMValue

include/caffeine/Solver/Solver.h, src/Solver/Solver.cpp
=> Rewrite Solver::evaluate to use LLVMValue instead of ContextValue

include/caffeine/ADT/PersistentArray.h, include/caffeine/IR/Operation.h, include/caffeine/Interpreter/Executor.h, src/Interpreter/Executor.cpp
This PR adds various mutex's in order to prepare for a multithreaded implementation of the Executor
=> Adding thread safety

.github/workflows/build-project.yml, src/Interpreter/Executor.cpp, src/Serialization/ValueIdMap.cpp
Build is borked - this should let us prevent that in the future.
=> Add clang to build matrix

docs/intrinsics.md
We're getting to the point where we have enough of these. They should probably be documented. This PR adds documentation for the first few.
=> Start documenting caffeine intrinsic functions

src/Interpreter/Interpreter.cpp
These are used by the codegen added as part of #294. See #296 for the full documentation on what this does.
I've copied the docs introduced here from #296 for an explanation
> ```llvm
> declare i8* @caffeine.resolve.p0i8.i64(i8* %ptr, i64 %len)
> ```
> This instructs the interpreter that we are going to be reading or writing to `%len` bytes starting at `%ptr`. This allows memory accesses using the returned pointer to be performed more efficiently since they can avoid having to query the underlying
SMT solver if constant folding works fully.
>
> Semantically, this function will always return `%ptr`. However, if the pointer does not point to a valid area then the entire path through the program will behave as if there was an invalid pointer access.
This PR is part of the work towards …
=> Introduce `caffeine.resolve.*` family of intrinsics

.github/workflows/build-project.yml, include/caffeine/Interpreter/Store.h, src/Interpreter/ExprEval.cpp, src/bin/caffeine.cpp
This should also fix the memory leak that was showing up in ASAN, although I haven't tested that.
Closes #293 
/stack #302
=> Fix build on MSVC

include/caffeine/IR/Assertion.h, src/IR/Assertion.cpp
As in title. I'll be using these in the following PRs in this stack.
=> Add missing operators to `Assertion`

include/caffeine/IR/Transforms.h, include/caffeine/Interpreter/Context.h, include/caffeine/Solver/CanonicalizingSolver.h, include/caffeine/Solver/SequenceSolver.h, include/caffeine/Solver/SimplifyingSolver.h, include/caffeine/Solver/Solver.h, include/caffeine/Solver/Z3Solver.h, src/IR/Transforms/canonicalize.cpp, src/IR/Transforms/simplify.cpp, src/Interpreter/Context.cpp, src/Solver/CanonicalizingSolver.cpp, src/Solver/SimplifyingSolver.cpp, src/Solver/Solver.cpp, src/Solver/Z3Solver.cpp, test/unit/IR/Transform/canonicalize.cpp
This PR modifies `Context` to now use `AssertionList` and then changes all the dependent things to also use `AssertionList`.
/stack #326
=> Change `Context` to use `AssertionList`

cmake/CaffeineTemplateCMakeLists.txt.in
=> Rename STEP_TARGET -> STEP_TARGETS

src/Solver/Z3Solver.cpp
As in title. This also avoids creating `z3::tactic` instances unnecessarily as that is quite expensive.
This is part #335
=> Elide Z3 solver calls if the result is already known

src/Interpreter/Context.cpp
=> Add support for zero-argument `main` functions

include/caffeine/Memory/MemHeap.h, include/caffeine/Memory/MemHeap.inl, src/Interpreter/ExprEval.cpp, src/Interpreter/Interpreter.cpp, src/Memory/MemHeap.cpp, test/run-pass/mem/global-mem-readwrite.c, test/unit/Memory/MemHeap.cpp
As per comments from last PR I changed the boolean flag to an general enum type
Fixes #180
=> [180] Add writable memory permissions and checks

src/IR/Operation.cpp, src/IR/Operation.h
When making this it turns out that I forgot to actually set it up and enable it. This PR does so. In addition, I found that repeatedly caching the hashes of `FixedArray` instances for every store makes them *extremely* slow. As such, I've opted them out of interning.
=> Actually get Operation cache working

scripts/gen-yarpgen-tests.sh
Forgot to include these in the other PR.
=> One last yarpgen fix

include/caffeine/Interpreter/Interpreter.h, src/Interpreter/Interpreter.cpp, test/run-pass/switch.ll
As in title. The implementation is pretty straightforward. I've included a test case to ensure that the preconditions for the path work as expected.
=> Implement `switch` instruction

docs/intrinsics.md
=> Write overall docs for caffeine_assert and caffeine_make_symbolic

src/IR/Operation.h
General symbolic arrays are quite slow in Z3. This optimizes them by replacing them with a set of select operations for small arrays.
=> Convert symbolic loads to `select` chains for small fixed arrays

docs/notes/profiling.md
I had to figure out how to properly profile caffeine so I figured I'd document it. This PR adds some notes on what it took to get it to work for me.
=> Add notes on how to profile caffeine

CMakeLists.txt, cmake/CaffeineDependencies.cmake
Turns out the last fixes I did didn't quite work. This fixes them again.
=> Fix cmake again

include/caffeine/Support/DiagnosticHandler.h, src/Support/DiagnosticHandler.cpp, src/bin/caffeine.cpp
=> Extract DiagnosticHandler from caffeine bin

scripts/gen-yarpgen-tests.sh, test/CMakeLists.txt
This just updates the gen-yarpgen-test script to allow configuring the output directory and gives it a proper command line interface.
=> Update gen-yarpgten-test scripts

docs/notes/coverage.md
This PR adds docs for how to get coverage reports from our tests.
=> Add instructions for getting coverage

.github/scripts/setup-env.sh, .github/workflows/build-project.yml, .github/workflows/find-coverage.yml, CMakeLists.txt, Dockerfile, cmake/CaffeineCoverage.cmake
This PR attempts to add coverage reports to CI using codecov
=> Add coverage reports to CI

test/unit/Support/Assert.cpp
As in title. It wasn't tested before so this should help get our test coverage up :P
=> Add tests for CAFFEINE_ASSERT

docs/notes/coverage.md
This PR reflects recent changes to the cmake configuration step
=> Update coverage documentation

test/run-pass/inst/extractvalue/const-array.ll, test/run-pass/inst/extractvalue/const-struct.ll, test/run-pass/inst/extractvalue/const-zero-struct.ll, test/run-pass/inst/inttoptr/roundtrip.ll, test/run-pass/mem/global-undef-array.ll, test/run-pass/mem/global-zeroinitializer-array.ll, test/unit/CMakeLists.txt, test/unit/Interpreter/ExprEval.cpp, test/unit/Interpreter/ir-with-global.ll, test/unit/Support/UnsupportedOperation.cpp
This adds coverage for `ExprEval.cpp`. I stopped once I hit 2%, there's still more that could be added.
Closes #430
=> Add tests covering `ExprEval.cpp`

test/unit/ADT/SharedArray.cpp
Tests to cover 80+% of `SharedArray.cpp`
=> Shared array tests

.github/scripts/setup-ccache.sh, .github/workflows/build-apt.yml
The current caching implementation doesn't quite work. This subs in ccache for the caching step.
=> Use ccache in build step

CMakeLists.txt, cmake/CaffeineLinting.cmake, include/caffeine/ADT/Guard.h, include/caffeine/Interpreter/Options.h, src/Memory/Allocator.cpp, tools/opt-plugin/test-main/plugin.cpp
This PR adds `clang-tidy` as a linter to Caffeine
=> Add linting to Caffeine

cmake/CaffeineLinting.cmake
Needed to copy and paste a couple of lines from one command to another
=> Fix linting

.github/scripts/update-alternatives-llvm.sh
The script wasn't working correctly on my system. This changes it to make all the tools their own masters.
=> Change update-alternatives script to avoid slaving certain tools

.codecov.yml
=> Set `codecov` patch coverage to 0

docs/notes/bazel.md
As in title. This is pretty small and meant to be added onto as other people find things they don't know.
=> Add note explaining how to do common tasks within bazel

src/Interpreter/Interpreter.cpp
This one is pretty straightforward, it switches up `visitAllocaInst` to use the helpers introduced in #558 and that makes the whole method implementation pretty straightforward.
/stack #558
=> Convert `Interpreter::visitAllocaInst` to use `InterpreterContext`

src/Interpreter/Interpreter.cpp
=> Convert visitStoreInst to use IntepreterContext

include/caffeine/Interpreter/ExternalFunction.h, include/caffeine/Interpreter/Interpreter.h, src/Interpreter/CaffeineContext.cpp, src/Interpreter/ExternalFuncs/CaffeineBuiltinResolve.cpp, src/Interpreter/Interpreter.cpp
As in title. Another straightforward refactoring.
=> Convert `caffeine_builtin_resolve` to an external function

WORKSPACE
The latest head has some changes that are useful to us.
=> Update hedron_compile_commands to latest head

bazel/clang-format.bzl
Previously, this would print some output if it found formatting errors and then exit with return code 0. Bazel would see the return code and helpfully suppress all the output produced by the test since it was assuming it passed. Now, the generated script will actually fail if the formatting is not valid.
=> [bazel] Make :check-format fail if formatting is invalid

include/caffeine/Interpreter/ExprEval.h, include/caffeine/Memory/MemHeap.h, include/caffeine/Memory/MemHeap.inl, src/Interpreter/ExprEval.cpp, src/Interpreter/Interpreter.cpp, src/Interpreter/PrintingFailureLogger.cpp, src/Memory/MemHeap.cpp, test/run-fail/mem/global-mem-readwrite.c
Previously we were allocating Read Only memory as Write only memory.
This PR fixes that.
/stack #596
=> Fix read write permissions

s-outputq:q
@brookedolny This was added as part of your PR. It seems like it's just the output from some command that was accidentally added. If this is actually meant to be there feel free to reject this PR :)
=> Remove temporary file that got committed

.github/workflows/build-apt.yml, .github/workflows/find-coverage.yml, CMakeLists.txt, README.md, libraries/libcxx/CMakeLists.txt
Due to some other changes, the Cmake build is currently broken (was
updating the libcxx compilation script)
=> Bump Cmake LLVM version to 12.0.0

src/Memory/Debug.cpp, test/run-pass/mem/BUILD, test/run-pass/mem/simple-malloc-free.c, test/run-pass/mem/symbolic-malloc-free.c, test/unit/Memory/MemHeap.cpp
This PR doesn't include an actual fix but after having made changes for debugging the test case passes now so I'm no longer sure what the issue is.
I'm including the changes here since they seem to fix the issue but I'm not actually sure why this happens.
/stack #523
=> Add some test cases for bug related to symbolic malloc

src/Solver/Z3/Convert.cpp, test/regression/issue-607.pass.requires-uitofp.c
=> Implement `UIToFp` support for `Z3Solver`

third_party/fmt/setup.bzl
As in title. I saw that a new release was made.
=> Update libfmt to version v8.1.0

third_party/immer/setup.bzl
=> Update immer to v0.7.0

src/Interpreter/ExprEval.cpp, src/Solver/Z3/Convert.cpp, test/regression/issue-604.pass.float-to-int-bitcast.c, test/regression/issue-604.pass.float-to-int-bitcast.ll
As in title. I originally used the test case from #604 but that needed even more intrinsics which aren't yet supported so I replaced it with a simpler one.
Closes #604 
Closes #591
=> Implement support for bitcasting between floats and integers

src/Interpreter/ExternalFuncs/CaffeineSymbolicAlloca.cpp
As in title. This should make the printed expressions reasonably smaller.
I'm not sure how to test this one so it is untested for now.
=> Represent small fixed-size symbolic allocations as a single constant

tools/caffeine/main.cpp
As in title. This should make it easier to debug test cases.
=> Add a command-line option to log all solver queries

bazel/bitcode.bzl
This commit changes how dependencies are linked in for bazel tests.
Currently, we link in libc and libc++ regardless of which language is
actually used. This is undesirable because `.ll` test files don't need
these deps and linking them in can cause builds to fail due to
redefinition of symbols.
=> Only link in stdlibs for appropriate languages

tools/caffeine/main.cpp
This fixes #633. It works by explicitly tracking whether a failure was due to an internal abort and overriding the error code if any failure was due to an unsupported operation.
Note that this has uncovered an existing instance of this failure so the tests will fail here. However, the fix for that is already present in #634 so I've decided not to make any changes here. I'll update once #634 is merged.
=> Make run-fail tests fail if they hit an unsupported operation

src/IR/Operation.cpp
=> Convert `SelectOp` to use `OperationData`

src/IR/Operation.cpp
=> Convert `AllocOp` to use `OperationData`

src/IR/Operation.cpp
=> Convert `LoadOp` to use `OperationData`

src/IR/Operation.cpp
=> Convert `StoreOp` to use `OperationData`

src/IR/Operation.cpp
=> Convert `Undef` to use `OperationData`

src/IR/Operation.cpp
=> Convert `UnaryOp` to use `OperationData`

include/caffeine/IR/EGraph.h, src/IR/EGraph.cpp
Pretty much as in title. These are some things that were sorta missed in the previous PRs so, instead of rolling them into the constant propagation PR, I've created this PR to address them separately.
/stack #685
=> Implement some utility methods for EGraph

include/caffeine/IR/EGraphMatching.h, src/IR/EMatching/Rewrites/Commutativity.cpp, test/unit/IR/EMatching.cpp
As in title. This PR includes the rule and can serve as a pilot case for further rewrites.
/stack #711
=> Implement a rewrite implementing commutativity rules

docs/notes/performance.md
After working on this for a bit I felt I should put some notes down on what makes caffeine slow, the key things we need to do to speed it up, and some notes on existing and possible optimizations.
=> Add some notes on performance optimizations

include/caffeine/IR/EGraphMatching.h, src/IR/EMatching/AllMatchers.cpp, test/unit/IR/EMatching.cpp
This PR implements the remaining rewrite rules. See the comments on the added methods for what they do.
/stack #718
=> Implement remaining e-graph rewrite rules

bazel/bitcode.bzl, bench/BUILD, bench/cpp_bench.cpp, src/Interpreter/Context.cpp, tools/caffeine/main.cpp
A few places had not accounted for c++ name mangling. This PR fixes that
=> Add support for c++ main method

include/caffeine/Interpreter/ExternalFunction.h, src/IR/OperationBuilder.cpp, src/Interpreter/CaffeineContext.cpp, src/Interpreter/Intrinsics/llvm.ctlz.cpp, test/run-pass/intrin/ctlz/BUILD, test/run-pass/intrin/ctlz/intermediate.c, test/run-pass/intrin/ctlz/maxval.c, test/run-pass/intrin/ctlz/zero.c
I'd like to use this for a demo so here's some test cases + an implementation.
=> Implement `llvm.ctlz.*` intrinsic

README.md, bench/BUILD, bench/bitcount.c
As in the title. I was meaning to have this ready for symposium but hopefully it'll still be useful for people that look at caffeine from now on.
Closes #500 
Closes #171
=> Update README with an explanation and an example

docs/notes/exceptions.md
Copying this from my blog because it might be useful for it to be in the repo too
=> Add C++ exceptions documentation

include/caffeine/Interpreter/ExternalFunction.h, src/Interpreter/CaffeineContext.cpp, src/Interpreter/Intrinsics/llvm.cttz.cpp, test/run-pass/intrin/cttz/BUILD, test/run-pass/intrin/cttz/exhaustive.c, test/run-pass/intrin/cttz/intermediate.c, test/run-pass/intrin/cttz/maxval.c, test/run-pass/intrin/cttz/zero.c
=> Implement `llvm.cttz.*` intrinsic
