insufficiently-caffeinated/caffeine

include/caffeine/ADT/Ref.h
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Type.h
include/caffeine/IR/Type.inl
src/CMakeLists.txt
src/IR/Operation.cpp
src/IR/Type.cpp
test/unit/ADT/Ref.cpp

This PR adds the expression IR. The design is (loosely) based off of the way LLVM's IR works but with a few key differences:
1. Everything is done through intrusive reference-counted pointers.
2. All IR nodes have exactly the same size and fields (so that they can be serialized to an array).
At the center of the design there are two main classes.
- The `Type` class represents the type of a value. It is currently stubbed out so I'll expand on this more once I've written the code for it.
- The `Operation` class represents an expression node. It consists of an opcode, a type, 0-3 operands, and in some cases, some constant data.
There are also a number of derived operation types that offer named accessors to the operands (e.g. `lhs` and `rhs` for BinaryOp).

Define expression IR

---

include/caffeine/IR/Assertion.h
include/caffeine/IR/Assertion.inl
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/Solver/Solver.h
src/IR/Assertion.cpp
src/IR/Operation.cpp
src/Solver/Solver.cpp
test/unit/IR/Assertion.cpp

This implements a fairly simple solver interface that has two main methods:
- `check`: Check whether the assertions are satisfiable and return `SAT`, `UNSAT`, or `Unknown` as applicable. This should be faster if a model isn't needed.
- `resolve`: Check whether the assertions are satisfiable and return a model that has the necessary assigned symbolic values.
It also adds an `Assertion` type (which is an expression that is always a boolean) and a new `Constant` expression that represents a symbolic constant.

Implement solver API

---

test/unit/CMakeLists.txt

This just means that all unit tests are shown when running ctest. It will still be necessary to run ctest with `--output-on-failure` to get the output when a test case fails.

Make ctest output show all unit tests

---

include/caffeine/ADT/Ref.h
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Type.h
include/caffeine/IR/Type.inl
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp
src/IR/Type.cpp

This is similar to LLVM's InstVisitor but for operations. This PR also adds hashing support to Type and Operation.

Add operation visitor

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp

I noticed that the opcodes for these existed but didn't have any of the needed support operations. This PR implements the needed methods. Note that it isn't currently formatted exactly to match the code style to avoid causing conflicts with #20. (The new code should be formatted correctly, there's some spacing removal that I've kept out as it's also included in #20)

Add create + visit methods for conversion opcodes

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Type.h
include/caffeine/IR/Type.inl
include/caffeine/IR/Value.h
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
include/caffeine/Solver/Solver.h
src/IR/Operation.cpp
src/IR/Type.cpp
src/IR/Value.cpp
src/Solver/Solver.cpp
test/unit/IR/Value.cpp

The logic to actually implement this is decently complicated (it requires walking the expression tree) an is entirely implementable using only the `Model::lookup` function. This PR implements `Model::evaluate` in terms of `Model::lookup`. Note that the implementation is still incomplete, I'll actually fill everything out in a follow-up PR.
To do this I found I needed to introduce a new `Value` as having the representation be an operation that's constrained to be either `ConstantInt` or `ConstantFloat` ended up being basically unusable for actually performing arithmetic. I've also changed the model interface to use `Value` as that made far more sense.
While doing this I went and added some utility methods to `Operation` and `Type` as I discovered that I needed them. As a result, there's …

Add default implementation of Model::evaluate

---

CMakeLists.txt
cmake/formatting.cmake

Our current check-format pass in CI doesn't work. This PR adds a target that will accurately check whether all files in the project are formatted and, in the case where it finds an unformatted file, print the diff between the formatted and unformatted files as the error message.
Note that this will only work on systems that have diff available on the command line.

Implement a check-format target

---

include/caffeine/IR/Assertion.h
include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
src/IR/Assertion.cpp
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp

This is a small refactor so that the set of assertions associated with a context can be used outside of the interpreter.

Move solver and assertions into Context

---

include/caffeine/IR/Operation.h
src/IR/Operation.cpp

This just adds some shortcuts for creating ICmp operations involving constants

Add shortcut methods for creating operations involving constants

---

include/caffeine/IR/Type.h
src/IR/Type.cpp

This introduces a new byte array type that is meant to be used as the backing store for an allocation. It also adds a utility method to get the size of a type in bytes, where it applies.
Byte arrays more or less correspond to a Z3 array so they don't actually have a size (it could be symbolic anyway), that will be added as part of the opcode.

[Memory 3/N] Add array type and byte_size member to Type

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp

This introduces 3 new derived opcode classes:
- `AllocOp` - allocates a new array that is initialized with copies of the same byte (meant to be used by alloca/malloc)
- `LoadOp` - loads a byte from an existing array
- `StoreOp` - returns an array with the byte at a given position overwritten with a new one
Beyond that, it adds support for numbered constants. Certain constants may not be user-facing (e.g. memory allocation addresses) and so they may not have a name that can easily be assigned. This mirrors Z3's API where constants can be either named or numbered. Also included is support for these new opcodes in `OpVisitor`
These are enough to implement the rest of the memory model. As part of this PR I also ended up compacting the opcode space somewhat which sorta blew up the number of …

[Memory 4/N] Implement allocation-related operations.

---

include/caffeine/IR/Visitor.inl
include/caffeine/Interpreter/Context.h
include/caffeine/Memory/MemHeap.h
include/caffeine/Memory/MemHeap.inl
src/Interpreter/Context.cpp
src/Memory/MemHeap.cpp

This PR is meant to implement enough memory support that it can be used within the interpreter.
Here's a list of the changes included in this PR
- Implement an allocation type that models allocations according to the design docs and provides methods to read and write memory as well as checking memory accesses.
- Implement a heap manager `MemHeap` that models allocation, deallocation, resolving pointers, and liveness checking.
- Implement a pointer type. `MemHeap` can be used to resolve these to concrete (allocation, pointer) pairs.
There are no tests at the moment. Being able to write tests is blocked on us having a solver that supports them (so need #19 to land first).
Stuff still TODO:
- Add support for `Load`, `Store`, and `Alloc` to the visitor within Model.
- Implement corresponding …

[Memory 5/N] Implement memory heap management

---

cmake/formatting.cmake
include/caffeine/IR/Operation.h
include/caffeine/IR/Value.h
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/FailureLogger.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Solver/Z3Solver.h
include/caffeine/Support/Macros.h
src/CMakeLists.txt
src/IR/Operation.cpp
src/IR/Value.cpp
src/Interpreter/Context.cpp
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/Solver/Z3Solver.cpp
src/bin/CMakeLists.txt
src/bin/caffeine.cpp

This PR has the following changes
- Add all the methods that were used be we forgot to implement
- Add a interface for logging failures
- Implement that interface to print out the constants in the model when executed
- More or less copy over the main binary
I have no idea if this runs because we haven't implemented enough of an interpreter to actually test anything.

Make everything compile and add main executable

---

include/caffeine/ADT/Ref.h
include/caffeine/IR/Operation.h
include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
interface/caffeine.h
src/IR/Operation.cpp
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp
src/bin/caffeine.cpp

This commit implements most of the non-controlflow opcodes we'll need for the demo although there's still a number left.
If we implement call and the builtins then we should be able to reuse the test suite from last time.

Implement more operations for the interpreter

---

include/caffeine/Solver/Z3Solver.h
src/Solver/Z3Solver.cpp
test/run-fail/collatz.c
test/run-fail/sample.c
test/run-fail/sdiv-nonzero.c
test/run-fail/sdiv-udiv-inequal.c
test/run-fail/sdiv-zero.c

This is necessary to implement the SelectOp in the interpreter, and pass the collatz test case

Add first pass of Z3Solver SelectOp

---

include/caffeine/ADT/SlotMap.h
test/run-fail/collatz.c
test/unit/ADT/SlotMap.cpp

This meant that any time we tried to iterate over a const `slot_map `it wouldn't return any values since we would always have that `std::begin(map) == std::end(map)`.
I've added an iteration test case although it wouldn't have caught this typo (it tests non-const iteration, the bug was in the const versions of the methods)

Fix typo within const slot_map::end

---

cmake/testutils.cmake
test/CMakeLists.txt
test/run-fail/CMakeLists.txt
test/run-fail/collatz.c
test/run-pass/CMakeLists.txt
test/skip-test.cpp

`select` isn't implemented so collatz cannot run. This adds cmake code to allow us to skip tests by putting `SKIP TEST` somewhere on the first line and then uses that to skip `collatz.c`.

Add cmake code to allow skipping tests

---

include/caffeine/IR/Operation.inl
include/caffeine/IR/Type.inl
include/caffeine/Memory/MemHeap.h
include/caffeine/Memory/MemHeap.inl

Calling `Constant::name` when the constant was numbered would previously just reinterpret the data there as a std::string. Now it just nicely explodes with a nice error message.
This also includes a few small unrelated fixes for missing includes/method implementations.

Add assertions for accessing Constant identifiers

---

src/bin/caffeine.cpp
test/unit/main.cpp

Note that this only happens if you disables googletest's default exception catching. However, it's useful when you're trying to debug test failures.
FYI to do this you need to do
```
$ ./test/unit/caffeine-unittest --gtest_catch_exceptions=0
```
but then test failure will print the exception message + the full stacktrace.

Show stacktraces in unit tests on failure

---

include/caffeine/Interpreter/FailureLogger.h
src/Interpreter/Interpreter.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/bin/caffeine.cpp
test/run-fail/collatz.c
test/run-fail/murmurhash3.c
test/run-fail/sdiv-udiv-inequal.c

The failure logger wasn't able to see the assertion used as an argument to `check`. This lead to not printing values that should have been asserted when running the fnv.c test case.
I also went through and cleaned up a few test cases that were coded to restrictions in decaf that no longer apply.

Give failure logger required context to see all assertions

---

include/caffeine/IR/Type.h
include/caffeine/IR/Type.inl
include/caffeine/IR/Value.h
src/IR/Value.cpp
src/Solver/Solver.cpp
test/unit/IR/Value.cpp

As in title. I have added 1 test case to ensure everything works but I can add more if we think they're needed.
Closes #62.

Implement support for Trunc, ZExt, SExt, and Bitcast within Value and Model::evaluate

---

cmake/formatting.cmake
include/caffeine/IR/Type.inl
include/caffeine/Interpreter/Interpreter.h
src/IR/Operation.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp
src/Solver/Z3Solver.cpp
test/run-fail/fp/self-equality.c

This makes floating point values and computations work in most cases. Here's the list of what was changed
- Implement support for LLVM `fcmp` instruction
- Use Z3's builtin `isnan` checking functions since `x == x` apparently doesn't work as expected with NaNs.
- Add support for extracting floating point values to `llvm::APFloat`
- Allow creating constants from LLVM floating point literals.
- Add a test case verifying that `x != x` fails with NaNs.
There's still some quirks of LLVM that are unsupported here but those can go in a separate PR. (I do have uncommitted test cases which fail there).

(Mostly) make floats work

---

src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

This just fixes something I noticed when looking at the Z3Solver code.
As part of constructing Z3Model the entire constants map was copied. However, it was never used in the calling method after constructing the model so it could instead just be moved.

Elide unnecessary copy in Z3Solver

---

include/caffeine/Interpreter/Interpreter.h
src/Interpreter/Interpreter.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h
test/run-fail/fp/approx-sqrt.c
test/run-fail/fp/greater-than-all.c
test/unit/CMakeLists.txt
test/unit/Solver/Z3Solver.cpp

This adds support for floating point arithmetic opcodes and also uses the Z3 C interface for floating point operations that are not supported by the C++ interface.
Note: Conversion from Z3 values to APFloat is currently broken when the Z3 fpa is an infinity. Will hold off merging until I fix that.

Add support for floating-point opcodes

---

cmake/setup-warnings.cmake
include/caffeine/ADT/Ref.h
include/caffeine/ADT/SlotMap.h
include/caffeine/IR/Visitor.inl
include/caffeine/Support/Macros.h
src/Memory/MemHeap.cpp
src/Solver/Z3Solver.cpp

This fixes a few errors that aren't enforced by gcc or clang as well as resolves a number of warnings that only show up in MSVC

Make everything compile with MSVC

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

I've been trying to implement vector operations and found that I needed this. I'm pulling it out here so that it can be reviewed separately.
For the moment I've approximated the semantics of the undef opcode within Z3 by just returning a constant 0. In the future we should probably look deeper into what's needed to properly handle undefs in LLVM.

Implement undef operation

---

include/caffeine/IR/Operation.h
src/IR/Operation.cpp
src/IR/Operation.h

This implements constant folding as part of expression construction. That is, when you call the corresponding `CreateXXX` method with constant operands it'll automatically do the proper constant folding. This means that no other code needs to be changed to take advantage of this.
This PR is dependant on #73 and includes its commits as well.

Implement basic constant folding

---

src/bin/caffeine.cpp

I ran into this while trying to hand-write some LLVM IR test cases. Right now it's changed a failure to just abort instead of returning a failing value. In the future we should have cmake check that the return code is a specific value instead.

Make sure that run-fail tests with bad input are marked as failed.

---

src/bin/CMakeLists.txt

This makes it easier to run it from the command line when needed.

Move caffeine-bin to root directory

---

include/caffeine/Interpreter/Value.h
include/caffeine/Interpreter/Value.inl
src/Interpreter/Value.cpp

This is an attempt to break apart bits of #76 into more reviewable chunks.
This part adds a new value representation for program values (which can be vectors or scalars at the moment). It isn't currently used anywhere within the program but will get used in the next PR. It also adds a method to map over these new values which is meant to make it easier to implement the visitor method. For examples of how it's used see the other PR.

Add ContextValue

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Type.h
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp
src/IR/Operation.h
src/IR/Type.cpp

This is a prerequisite for supporting just about any other memory operations. I've also modified the array type so that it stores the bitwidth of the integer type used to index into the array.
This is a first step towards closing #82.

Add ConstantArray operation

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

Some of the changes made in #84 mean that we can actually delete a bunch of `Operation` constructors without modifying the dependent code. This PR does that.
Currently depends on #84 and so includes it's code. I'll rebase to remove that once #84 merges.

Cleanup Operation constructors

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/Context.cpp
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp
test/run-fail/interleave.c
test/run-fail/vector/extractelement1.ll
test/run-fail/vector/shufflevector1.ll
test/run-pass/vector/shufflevector2.ll

Does a few things:
- Change the representation of values within `Context` to support having vectors
- Change all existing LLVM opcode implementations to work with this
- Implement the new vector opcodes required to run the added test cases (`insertelement`, `extractelement`, and `shufflevector`)

Add vector support

---

include/caffeine/ADT/SharedArray.h
src/ADT/SharedArray.cpp
test/unit/ADT/SharedArray.cpp

This is basically a modifiable byte array that efficiently shares it's contents between instances. It does this by storing a base value along with changes to that base array (and it does that recursively). This means that when a `SharedArray` is copied it will only copy at most a small amount of data.
I've also included a few small optimizations:
- If there's fewer than 64 elements/modifications in the copy source then we just copy the entire array. This should help avoid building a large linked list with only a single change at each level which would be inefficient.
- If the number of modified elements is greater than 80% of the total size, then just flatten the array and work with that.
These factors still need to be tuned but we can revisit that when doing performance work at a later …

Create shared byte array data structure

---

include/caffeine/ADT/SharedArray.h
include/caffeine/IR/Value.h
src/ADT/SharedArray.cpp
src/IR/Value.cpp
test/unit/ADT/SharedArray.cpp

Using the `SharedArray` introduced in #93 this adds support for byte array values. I've then gone and implemented the `load` and `store` value operations.
Closes #53.
Note: this PR depends on #93 and currently includes all it's changes. When reviewing ignore any changes to `SharedArray.[h|cpp]` as those are being reviewed in the other PR and there's no point rehashing that here :)

Add support for byte array Value instances

---

include/caffeine/IR/Type.inl
include/caffeine/Memory/MemHeap.h
src/Memory/MemHeap.cpp
test/unit/Memory/MemHeap.cpp

Here's the things that got updated as part of this:
- Explicitly check that the pointer is not null when performing a validity check
- When allocating a new heap allocation the caller now needs to pass in the data
The second one is needed to create allocations with preexisting data (e.g. global arrays).

Update MemHeap to be usable as part of memory support

---

include/caffeine/Interpreter/Interpreter.h
src/Interpreter/Interpreter.cpp

As in description. The getelementptr instruction corresponds to member accesses, array accesses, etc. At the moment I haven't implemented support for vector getelementptr instructions since I'm not entirely sure how they work.
This PR depends on #99, #98, and #97 and includes all of their changes. I'll rebase to remove those as they get approved.
Closes #100.

Implement getelementptr instruction

---

include/caffeine/Interpreter/StackFrame.h
src/Interpreter/StackFrame.cpp

This silences the one warning we have in the project under clang.

Remove unused private field from StackFrame

---

src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
test/run-pass/mem/const-getelementptr.c

Turns out that you can apparently just shove any old set of LLVM operations into a constant expression. This is annoying since it means that I have to duplicate a whole bunch of code from the interpreted but make it different enough that they can't share.
Anyway, this implements it by just building the corresponding set of expression trees and letting constant folding take care of the rest. 
Here's the detailed set of changes in this PR:
- Refactor the constant handling code out into it's own source file. It was getting rather big and seemed like it would be better off as a somewhat independent module.
- Allow `icmp` to work with pointer operands.
- Add a test case that involves both of the above.
Edit: The refactor has been split out into #111

Implement support for LLVM expression constants

---

CMakeLists.txt
cmake/LLVMIRUtils.cmake
cmake/clang-build.cmake
cmake/clang-link.cmake
interface/CMakeLists.txt
test/run-fail/CMakeLists.txt
test/run-pass/CMakeLists.txt

When writing the code for malloc and free I needed to be able to link some runtime IR into the final bitcode for test cases. This PR adds the required code to be able to have LLVM IR libraries that are linked together.
It works by defining new cmake languages that compile to llvm bitcode and a linker language that shells out to llvm-link to link it all together. I've also rewritten the test cmake files to use the new methods.
See the explanatory comments within `LLVMIRUtils.cmake` for a bit of how it works but TBH it's probably not worth trying to understand it all.

Rewrite cmake build steps for LLVM IR makefiles

---

include/caffeine/Interpreter/Interpreter.h
src/IR/Operation.cpp
src/IR/Operation.h
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/Value.cpp
src/Memory/MemHeap.cpp
test/run-fail/mem/select-array.c
test/run-pass/mem/pointer-bitcast.c

This implements a limited version of the bitcast instruction that only supports pointers. 
I've added a test case but it's currently marked as skipped because #113 hasn't landed.

Implement bitcast instruction

---

include/caffeine/IR/Operation.h
include/caffeine/Interpreter/Interpreter.h
src/IR/Operation.cpp
src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
test/run-fail/mem/allocations-anywhere.c

Mostly as in title. Here's the detailed list of changes:
- Added some utility operation factory functions (`CreateTruncOrZExt` and `CreateTruncOrSExt`) that behave as named
- Implement inttoptr
- Implement ptrtoint
- Fix the constant evaluation logic for both opcodes

Implement inttoptr and ptrtoint

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/Options.h
include/caffeine/Memory/MemHeap.h
interface/caffeine-builtins.c
src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h
test/run-pass/mem/malloc-free.c

Pretty much as in title. 
Implements `malloc` and `free` by implementing two builtin functions `caffeine_malloc` and `caffeine_free` and then using an external module to implement the required behaviour of `malloc` and `free`. 
Closes #83. Closes #107.

Implement malloc and free

---

cmake/testutils.cmake
test/run-fail/CMakeLists.txt
test/run-pass/CMakeLists.txt

There's two benefits to this:
- We only need to make changes in 1 place when we need to modify the cmake configuration of the tests
- The output IR files now mirror the input files in directory structure which is quite useful when running them manually
- I managed to make some of the used values a bit less dependent on directly structure
Other than that the change is mostly copy-paste.

Refactor cmake test declaration scripts

---

CMakeLists.txt
include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/StackFrame.h
include/caffeine/Memory/MemHeap.h
include/caffeine/Memory/MemHeap.inl
src/Interpreter/Context.cpp
src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
test/run-fail/CMakeLists.txt
test/run-fail/mem/alloca-escaped.c
test/run-fail/mem/free-stack-alloca.c
test/run-pass/mem/alloca-basic.c
test/unit/Memory/MemHeap.cpp

Here's what was changed:
- We now have support for the `llvm.lifetime.(start|end).*` intrinsics. They have no effects and so they're ignored.
- Allocations now have a kind to verify that the right deallocation method is being used. (e.g. so we can emit errors if someone tries to free a global or stack allocation)
- Extra logic to delete stack allocations upon returning from a function
- And of course, implementing the alloca instruction itself
I've also discovered that cmake versions 3.17+ allow you to add flags to the ctest invocation so I've configured it to add the `--output-on-default` flag if using a supported version.
Closes #50.

Implement alloca instruction

---

include/caffeine/IR/Operation.h
src/IR/Operation.cpp
src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp

It takes a lot of typing to create a binary operation with a constant integer operand. This PR adds methods that remove some of the useless boilerplate.
Specifically, for each `CreateXXX` method in `BinaryOp` there are now two more overloads that allow passing an integer in on each side. I've also gone through the codebase and simplified all the places where the new methods could apply.

Miscellaneous refactoring

---

include/caffeine/Memory/MemHeap.h
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
test/CMakeLists.txt
test/regression/CMakeLists.txt
test/regression/issue-103.fail.write-spans-allocation-boundary.c
test/regression/issue-103.pass.write-at-end-of-allocation.c
test/unit/Memory/MemHeap.cpp

Previously a read that was only partially within an allocation wouldn't trigger an error but would instead just silently delete that branch. That was incorrect and it now will properly pass a test failure.
To make it easier to keep track of regression tests like this I've added a `test/regressions` folder with tests that are meant to be named in a defined format that makes it easier to keep look at the file name and find the relevant issue.
Closes #103

Check read width when validating pointers

---

include/caffeine/Interpreter/Interpreter.h
interface/caffeine-builtins.c
src/Interpreter/Interpreter.cpp
test/run-pass/mem/calloc-is-all-zero.c

As in title.
The implementation is basically a copy-paste implementation of malloc except that the memory is initialized to zero.
Closes #128.

Implement calloc

---

include/caffeine/ADT/PersistentArray.h
test/unit/ADT/PersistentArray.cpp

Our current representation of such arrays is really slow. If we know the length of the array then we can use a more efficient representation that avoids making array value lookups go through z3 a lot of the time.
This PR adds a new data structure, called a `PersistentArray`. It's an array that shares the underlying data between multiple instances but also allows those instances to accept writes without the writes being shared.
The majority of the complicated implementation details happen within the `PersistentArray::Node` class, as well as the `get` and `set` methods. A lot of the rest is just boilerplate.

[1/2] Optimize internal representation of known-size symbolic arrays

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Visitor.h
src/IR/Operation.cpp
src/Interpreter/CtxConstEval.cpp
test/run-pass/mem/global-int-store.c

This fixes one of the issues discovered while running the test cases generated by #148. Specifically we don't support globals that don't derive from `ConstantData`.
Here's the summary of the changes that were added to make this work:
- Added a pure virtual `ArrayBase` operation so that it's possible to get the size of an array generically. 
- Implemented global evaluation by evaluating the constant itself and then storing writing it to a data array.
I haven't implemented support for vector stores yet since what that will actually entail hasn't been worked out yet. I've added a simple test case but most of the behaviour here makes use of other, already tested, work.

Implement non-ConstantData globals

---

src/Interpreter/CtxConstEval.cpp
test/run-pass/mem/global-zeroinitializer.c

This adds support for globals initialized using the `zeroinitializer` LLVM IR keyword. Also includes a test case.

Implement zeroinitializer globals

---

src/Interpreter/CtxConstEval.cpp

For a number of yarpgen tests the majority of the time is spent resolving pointers that don't already have an associated allocation.
This was made worse by the fact that constant getelementptr instructions were stripping out the attached allocation. This is just a point fix to keep the corresponding allocation.
In short, it's a 1-line change that gives a 50%+ performance boost on common memory access operations.

Keep pointers resolved for constant getelementptr operations

---

src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp

Currently the constraints we generate during allocation are rather inefficient. This PR changes them to be simpler while still remaining correct. It also cuts out some allocations that are redundant but make the solver do extra work.
In terms of performance it improves the runtime of the `vector-load-store` test from #151 from 18s down to 2s.

Optimize allocation constraints

---

include/caffeine/ADT/PersistentArray.h
src/ADT/PersistentArray.cpp
test/unit/ADT/PersistentArray.cpp

This PR fixes some issues that cropped up within the implementation of PersistentArray. Notably, if you used the vector move constructor it would initialize the size to 0 even if the vector contained elements.

[2/N] Optimize internal representation of known-size symbolic arrays

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

This adds a `FixedArray` opcode that is a more efficient implementation of a fixed-size array.
Currently depends on ~all my other PRs and still WIP so keeping as draft for now.

[3/N] Optimize internal representation of known-size symbolic arrays

---

include/caffeine/ADT/Ref.h

Turns out that they were missing some required bits.

Fix compilation errors when trying to use rvalue ref methods

---

include/caffeine/IR/Type.h
include/caffeine/IR/Type.inl
include/caffeine/IR/Value.h
include/caffeine/Solver/Solver.h
src/IR/Type.cpp
src/IR/Value.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp

Copy pasted from #173:
The Model superclass evaluate expressions, and its subclasses just take care of lookups of constants in various solvers. The implications of this is that `evaluate` doesn't need to be `virtual` and `lookup` should be protected.
Also add some documentation for class to explain that.
Finally we want an overload for `evaluate(ContextValue)` for easier access.

Refactor the model class

---

include/caffeine/IR/Matching.h
include/caffeine/IR/Operation.h
test/unit/IR/Matching.cpp

Pretty soon we're going to want to perform various query optimizations. As part of this we'll need an easy way to check if an expression is an expected expression tree. This PR is the first part of what's needed for that. It adds a (somewhat) complete set of patterns along with methods to use them.
To see how this code is supposed to be used check out the docs on `matches` and `matches_anywhere`.

Implement expression-tree matching utilities

---

CMakeLists.txt
interface/CMakeLists.txt
libraries/CMakeLists.txt
libraries/builtins/CMakeLists.txt
libraries/builtins/caffeine-builtins.h
libraries/builtins/memory.c

I figure that we're going to have a number of libraries beyond the basic builtins stuff so moving it to a separate folder just made sense.

Move builtins to their own folder within the libraries folder

---

include/caffeine/Memory/MemHeap.h
src/Memory/MemHeap.cpp

As in title. No longer needed to support memcpy but useful anyway.

Add support for symbolic sizes in memory helper methods

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

This allows you to create an operation with the same opcode and type as an existing one while replacing the opcodes with new ones.

Implement some more utility methods for Operation

---

include/caffeine/Solver/Solver.h
include/caffeine/Solver/Z3Solver.h
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp

It's useful more broadly than `Z3Solver` and this will allow it to be used as such.

Move EmptyModel from Z3Solver.cpp to Solver.h

---

include/caffeine/Interpreter/Context.h
src/Interpreter/Context.cpp
src/Interpreter/PrintingFailureLogger.cpp

This is less useful for our test cases but as they get bigger it's a useful capability to have. In the future we could get it down to the source code line when debuginfo is present.

Modify PrintingFailureLogger to print a backtrace of the symbolic program

---

include/caffeine/Interpreter/Interpreter.h
libraries/builtins/string.c
src/Interpreter/Interpreter.cpp
test/run-pass/mem/memcpy-basic.c
test/run-pass/mem/memmove-basic.c

This PR implements the `memcpy` and `memmove` intrinsics by forwarding them to some C functions defined within the `caffeine-builtins` library.
Closes #135.

Implement memcpy and memmove intrinsics

---

include/caffeine/Solver/SequenceSolver.h

Basically it keeps trying new solvers until one of them returns something other than `Unknown`. This is meant to be used for combining multiple simplifying solvers. (i.e. ones that just modify the assertions and never actually solve the expression)

Implement solver which composes other solvers

---

include/caffeine/IR/Transforms.h
include/caffeine/Solver/DecompSolver.h
src/IR/Transforms/decompose.cpp
src/Solver/DecompSolver.cpp
test/unit/IR/Transform/decompose.cpp

This adds a new intermediate solver, DecompSolver, that breaks down top-level assertions into multiple smaller ones that are 
to the original assertion.
The transforms currently implemented are
```
- true          -> nothing
- and(a, b)     -> a, b
- not(or(a, b)) -> not(a), not(b)
```
By itself this solver doesn't give a large gain but it's an important building block towards others that do. The actual details of the decomposition algorithm have been put in a separate method exposed through `IR/Transforms.h`. Unit tests are also included.
Draft since it depends on #157, #187, and #176.

Implement expression decomposition solver

---

include/caffeine/IR/Matching.h
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl
src/IR/Operation.cpp
src/Interpreter/CtxConstEval.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

Reasons for removal:
- Its functionality has been superseded by `FixedArray`
- It doesn't work as well with constant folding as `FixedArray` does.
- It cannot be modified to support operand indexing arrays (`FixedArray` can)
In short, it's a special case that doesn't end up carrying it's weight so it should be removed. I'd also like to have the operation name for denoting symbolic arrays but I think it's worth removing `ConstantArray` either way.

Remove ConstantArray Operation

---

CMakeLists.txt
cmake/CaffeineLinking.cmake

It doesn't make a lot of sense to use LTO when in debug mode since no optimizations are being done. This PR changes to only be specified when not in debug mode.

Only build with ThinLTO in release mode

---

include/caffeine/ADT/PersistentArray.h
include/caffeine/IR/Matching.h
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/Support/CopyVTable.h
src/IR/Operation.cpp
src/Solver/Solver.cpp
src/Support/CopyVTable.cpp
test/unit/IR/Operation.cpp

In current master FixedArray doesn't behave like any of the other operation classes. This PR changes it to align with the way other classes are used and removes special casing elsewhere within the code.
Detailed list of changes:
- Add code to copy the class vtable pointer when an `Operation` instance is copied
- Override a number of member functions within `Operation` so that they work when the derived type is a `FixedArray` instance.
- Ensure that the vtable is copied when calling `with_new_operands`
- Expose some new methods on `PersistentArray` to support the operations that `FixedArray` needs
See the docs on `CopyVTable` for some of the restrictions on using it properly.

Remove special-casing for FixedArray

---

include/caffeine/IR/Transforms.h
include/caffeine/Solver/CanonicalizingSolver.h
src/IR/Transforms/canonicalize.cpp
src/Solver/CanonicalizingSolver.cpp
test/unit/IR/Transform/canonicalize.cpp

This is a solver that attempts to convert expressions to a canonical form. We haven't really defined what we want out of a canonical form yet so all the solver does right now is eliminate duplicate assertions and remove unevaluated constant subexpressions.

Implement canonicalizing solver

---

CMakeLists.txt
cmake/CaffeineDependencies.cmake
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/CMakeLists.txt
src/IR/Operation.cpp
vcpkg.json

This replaces the previous error-prone switch statement with a use of the [`magic_enum`](https://github.com/Neargye/magic_enum).
Detailed list of changes:
- Replace giant switch within `Operation.cpp` with magic_enum
- Use FetchContent to automatically get `magic_enum` if it's not available on the local system
It's not supported on all compilers so if not supported then it'll just return `"<usupported>"` as the enum variant name otherwise. We should maybe be emitting a warning in this case but that would take a decent amount of effort to make it work so I haven't done that here.

Use magic_enum library to avoid boilerplate switch statements

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

This is meant to make it easier to write code that just wants to deal with identifier of a constant without caring if it's a string or a number. I haven't changed any of the downstream callsites yet but new code should use `Symbol` if it doesn't need to care about the string vs number divide.

Implement Symbol type for constant names

---

include/caffeine/Solver/Solver.h
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

Now that we have a common type for constant identifiers we should be using it anywhere we would previously take a symbol name or number. This updates `Model::lookup` to use `Symbol` (and also adds a size parameter to support the upcoming ConstantArray operation).

Update solver API to use the Symbol type

---

Dockerfile

This PR adds capnp to the Dockerfile because dependant PRs won't pass the CI before this is done

Add Capnp to Dockerfile

---

include/caffeine/IR/Assertion.h
include/caffeine/IR/Assertion.inl
include/caffeine/IR/Matching.h
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/Interpreter/StackFrame.h
include/caffeine/Interpreter/Value.h
include/caffeine/Memory/MemHeap.h
include/caffeine/Memory/MemHeap.inl
src/IR/Assertion.cpp
src/IR/Operation.cpp
src/IR/Transforms/canonicalize.cpp
src/IR/Transforms/decompose.cpp
src/Interpreter/CtxConstEval.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp
src/Interpreter/Value.cpp
src/Memory/MemHeap.cpp
test/unit/IR/Matching.cpp
test/unit/Memory/MemHeap.cpp

In detail, this PR:
- Defines `typedef ref<Operation> OpRef` in `Operation.h`
- Replaces all instances of `ref<Operation>` with `OpRef`
- Formats everything
This is all automated and so shouldn't need to be reviewed line by line (the commits correspond to exactly those steps).
This is meant to be a first step towards making all operations references const throughout the codebase. The next PR will change `OpRef` to be a typedef for `ref<const Operation>` and fix whatever breakage occurs.

Replace ref<Operation> with OpRef typedef across whole codebase

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/IR/Operation.cpp
src/IR/Transforms/canonicalize.cpp
src/IR/Transforms/decompose.cpp
test/unit/IR/Matching.cpp

This is the second half of #220. It makes `OpRef` a typedef for `ref<const Operation>` and then fixes all the parts that broke due to that change:
- There was a `copy_vtable` call within `with_new_operands` that was using an operation that got changed to be const. This has been modified to be used by the newly-created non-const pointer.
- `canonicalize` was using non-const Operation pointers as keys in a map. This has been changed to use const Operation pointers.
- `decompose` was assigning to expression values (i.e. `*expr = *other`) instead of just assigning references. This has been changed to just assign references.
- Remove non-const `Operation::operator[]` since it no longer makes sense.
- One `matches_anywhere` test case relied on assigning to expression values. This has been …

Change OpRef to be a typedef of ref<const Operation>

---

include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl

As in the title. If we ensure that any generic algorithms that take a visitor use it as a function then we'll also be able to pass lambdas as a visitor which is a nice usability improvement where it's needed.
This is part of the work on #161.

Allow visitors to be used as function objects

---

CMakeLists.txt
src/CMakeLists.txt

There are cases where we'll want this ability - the current one I have is ensuring that debug methods don't get deleted even if they're unused. I've kept the defaults the same as before.

Allow libcaffeine to be built as a static or shared library

---

include/caffeine/IR/Operation.h
src/IR/Debug.cpp

This is a private method which prints a representation of the expression to stdout. It's meant to be used as an aid while debugging so I've left it as a private method.
Note that this only really works when caffeine is built as a shared library as enabled by #209.

Add private utility method to print an expression while in a debugger

---

include/caffeine/Support/CopyVTable.h
src/IR/Operation.cpp
src/Support/CopyVTable.cpp

As it turns out, the copy constructor for CopyVTable runs before the derived class actually initializes the derived vtable. This means that as soon as we actually start copying Operations around the vtable was not being copied around with them. This showed up once the code actually started copying operations around and not just moving refcounted pointers around.
The fix for this is to have Operation call copy_vtable within its ctors. I've prevented the same issue from (hopefully) occurring again by deleting the copy/move ctors of CopyVTable and documenting this footgun in the class documentation.

Fix use of CopyVTable within Operation

---

test/unit/CMakeLists.txt

If gtest catches exceptions thrown from tests then we don't get to see backtraces showing where the exception was thrown. This is normally a good thing since it allows up to keep running tests in the rest of the test suite. However, when running the tests from ctest we run each one individually so if an uncaught exception is thrown we want to just die and print out the backtrace.
This PR changes the default when running ctest.

Don't catch exceptions when running tests individually

---

include/caffeine/Interpreter/Interpreter.h
interface/caffeine.h
libraries/builtins/caffeine-builtins.h
libraries/builtins/make_symbolic.c
src/Interpreter/Interpreter.cpp
test/run-fail/make_symbolic/init-struct.c

This PR implements the `caffeine_make_symbolic` builtin. See the docs on the builtin for what it actually does.
I have also added a single test case to help verify printing and whether it actually works.
Closes #134

Implement caffeine_make_symbolic

---

include/caffeine/Interpreter/Interpreter.h
libraries/builtins/CMakeLists.txt
libraries/builtins/memset.ll
src/Interpreter/Interpreter.cpp
test/run-pass/mem/memset-basic.c

This implements the `llvm.memset` intrinsic when `sizeof(void*) == 8`. I was unable to write a version in C which didn't just get optimized down to the memset intrinsic so I had to write it using LLVM IR.
I have also included a simple test to ensure that things work as expected.
Closes #216.

Implement memset intrinsic

---

src/IR/Operation.cpp
src/IR/Operation.h

We'd like `with_new_operands` to apply constant folding rules when they apply to the expression formed with the new operands. Unfortunately, that's not possible to do with the current design since it's done as part of the `CreateXXX` methods. To allow it to be used more generally this PR moves all the constant-folding related code out into a separate visitor in `src/IR/Operation.h`.
With that change included we can now properly perform constant folding within `with_new_operands` calls. It also simplifies a bunch of the code so we end up getting a net reduction in lines of code!
This is a fairly large PR but it mostly involves copy and pasting code so I'm hoping review should just involve a skim of the changes.

Refactor constant folding out into a separate visitor

---

include/caffeine/IR/Transforms.h
include/caffeine/IR/Transforms.inl
test/unit/IR/Transform/rebuild.cpp

This adds a transform which allows a user-provided visitor to perform arbitrary transformations to the expression while rebuilding the modified expression tree. It's not super useful on it's own but it is a necessary building block to build more advanced transforms.
Leaving draft for now since this PR depends on #208.

Implement rebuild transform

---

include/caffeine/Memory/MemHeap.h

The allocation doc comment mentioned a field that no longer exists. I've removed that part of the doc comment and fixed up the rest.

Fix outdated doc comment for Allocation

---

src/IR/Debug.cpp

It should never be possible to have this happen in C++ but it's more useful to have DebugPrint print NULL when calling it in the debugger than causing a segfault in the middle of your debug session.
I ran into this while debugging and figured I'd fix it for good.

Handle the case where this is null in DebugPrint

---

include/caffeine/Interpreter/Value.h
include/caffeine/Interpreter/Value.inl
src/Interpreter/Value.cpp

This PR introduces a new value type (`LLVMValue`) for use within the interpreter. For now, it isn't used anywhere but future changes will expand it's use throughout the codebase until all uses of `ContextValue` have been replaced and we can delete `ContextValue`.
The main differences between `ContextValue` and `LLVMValue` are:
- `LLVMValue` only allows vectors to have scalar (either an operation or a pointer) values.
- `LLVMValue` treats scalars as a vector of length 1 which makes transformations over them much easier.
- `LLVMValue` has support for aggregates (struct and array)
To help with the incremental conversion I have also added conversion operators between `LLVMValue`, `LLVMScalar`, and `ContextValue` so that we can easily convert between them at boundaries.
This PR is part of the …

[1/N] Interpreter redesign - Redesign ContextValue

---

include/caffeine/Memory/MemHeap.h
src/Memory/MemHeap.cpp

Basically as in the title. The new overloads also properly handle struct and array values.
This PR is part of the effort to redesign the whole interpreter (#202)
Depends on #228.

[2/N] Interpreter redesign - Implement Allocation::write overloads for LLVMValue and LLVMScalar

---

include/caffeine/Interpreter/Value.h
src/Interpreter/Value.cpp

As in title. Should mirror the printing format of `ContextValue`.
Depends on #228

Implement operator<< overloads for LLVMValue and LLVMScalar

---

src/IR/Operation.cpp

As in title. Currently this causes an assert, this PR fixes that to print correctly for any number of operands.

Fix operand printing in cases where an operation has > 3 operands

---

include/caffeine/Interpreter/ExprEval.h
include/caffeine/Interpreter/StackFrame.h
include/caffeine/Interpreter/Value.h
src/Interpreter/ExprEval.cpp

This PR adds a visitor that generates `LLVMValue`s. It is intended to unify logic between CtxConstEval and Interpreter and eventually replace a decent chunk of both. Currently all that is implemented are some simple LLVM instruction opcodes. The next couple PRs will expand `ExprEvaluator` to support everything currently supported by the constant evaluation code.
This PR is part of the effort to redesign the whole interpreter (#202)
Depends on #228.

[3/N] Interpreter redesign - Introduce simple expression evaluator

---

include/caffeine/IR/Matching.h
include/caffeine/IR/Transforms.h
include/caffeine/Solver/SequenceSolver.h
include/caffeine/Solver/SimplifyingSolver.h
src/IR/Transforms/simplify.cpp
src/Solver/SimplifyingSolver.cpp
src/bin/caffeine.cpp

This PR implements the start of a generic expression simplification solver. Currently all it is able to do is run the decomposition transform and replace with constants when it finds an `x == <const>` constraint within the assertions. In the future this should be expanded as needed.
Closes #161.

Implement expression simplification solver

---

include/caffeine/Interpreter/Value.h
src/Interpreter/Value.cpp

This PR adds a `broadcast` method to `LLVMScalar` which can be used to create a vector of containing the scalar repeated `n` times.
Depends on #228

[6/N] Interpreter redesign - Implement vector broadcast for LLVMValue

---

cmake/CaffeineDependencies.cmake
cmake/FindZ3.cmake

The main contributors that I found to cmake configure being slow were two different non-required calls to find_package that didn't succeed. These took on the order of a few hundred milliseconds which noticably slowed down the configure step.
To remedy this I cached the failure value in cases where the find_package calls failed but we were able to successfully find the library somewhere else. This seems to have halved the time we spend on running cmake configures when I try it locally.
This was annoying me so I decided to go and fix it.

Optimize cmake configure step

---

cmake/CaffeineFormatting.cmake

This allows it to run faster when you've only changed a few files.
I don't have hard numbers but previously running a format always took on the order of about 10 seconds for me but now it takes ~2s even with the yarpgen files that I have in my repo (which are usually slower to format).
You still only have to run `make format` but now it can parallelize the individual calls to `clang-format`

Optimize format target by splitting it into multiple internal targets

---

include/caffeine/Interpreter/ExprEval.h
src/Interpreter/ExprEval.cpp

This version of `getelementptr` is an improvement over the one in CtxConstEval since it works properly when some or all of the operands are vectors.
This PR is part of the effort to redesign the whole interpreter (#202).
/stack #233

[7/N] Interpreter redesign - Implement support for getelementptr in ExprEvaluator

---

include/caffeine/Support/LLVMFmt.h

This means that we can now print supported llvm types using libfmt like so
```
const llvm::Instruction& inst = ...;
fmt::print(std::cout, "{}", inst);
```
I've added support for everything derived from `llvm::Value` or `llvm::Type` as well as `llvm::APInt` and `llvm::APFloat`.

Add support shim for printing LLVM types using fmt

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/Context.cpp
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/Interpreter/StackFrame.cpp
src/Solver/Solver.cpp

This makes a number of members of both `Context` and `StackFrame` and then cleans up the code that needs to be changed because of that.
Note that most of these were already effectively public due to the accessor methods available so this mostly just makes things cleaner.
This PR is part of the effort to redesign the whole interpreter (#202).
/stack #238

[10/N] Interpreter redesign - Clean up Context and StackFrame

---

include/caffeine/Interpreter/ExprEval.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp

This lets us delete a large amount of code within Interpreter and instead use the common code within ExprEvaluator.
/stack #240

[11/N] Interpreter redesign - Use ExprEvaluator to implement simple operations within Interpreter

---

include/caffeine/Interpreter/ExprEval.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
test/run-pass/inst/select/vector-select.ll

This also makes select work according to the LLVM docs when the arguments are vector values. I've added a test case to cover that.
Accidentally closed this since I deleted the base branch - am reopening.
/stack #246

 Move select instruction implementation to ExprEvaluator 

---

include/caffeine/Interpreter/ExprEval.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp

As in title. No new features but the implementations become a bit simpler with the new semantics associated with LLVMValue.
Accidentally deleted this due to deleting the base branch - am reopening.
/stack #246

Move vector insert, extract, and shuffle to ExprEvaluator 

---

test/run-fail/fp/approx-sqrt.c

This currently takes an extremely long time to run. Until we figure out why we're better off disabling it.

Skip run-fail/fp/approx-sqrt test

---

include/caffeine/IR/Operation.def
include/caffeine/IR/Operation.h
include/caffeine/IR/Visitor.h
include/caffeine/IR/Visitor.inl

I've discovered that we're missing implementations of a number of different visitor methods. Since this will probably happen again if we're manually declaring new opcodes I've instead gone and added a definitions file (similar to LLVM's `Instruction.def`) that we can use to generate code by specifying some macros.
This PR rewrites Visitor and Operation to make use of it. I will add some more follow-on PRs to add it to everywhere that should use it and also to add some implementations for the missing opcodes identified.
This is the first step towards fixing #262

Centralize declaration of Operation opcodes

---

.github/workflows/build-project.yml
Dockerfile

Currently backtraces given in CI are useless - this changes CI to build everything in the `RelWithDebInfo` cmake profile. It also adds clang-format to the CI docker image.

Update CI to build things with debug info

---

src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h
test/run-pass/inst/store/roundtrip-float-store.ll

Turns out we haven't implemented bitcasts so load/store of floating point values doesn't work. This PR adds support for this with one more general caveat: Z3 doesn't track NaN payloads so it isn't possible to round-trip an integer through a float and expect the value to remain the same.
The logic for bitcasting an int to a float is somewhat finicky here. Luckily I can run a symbolic test with all possible values to ensure that it is correct :P
Fixes #262

Implement bitcast operation within Z3

---

src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp

It didn't feel worthwhile to create multiple PRs for this. Summary:
- Add a better assert message if the pointer to the name in `caffeine_make_symbolic` resolves to nothing
- Add an assertion if someone tries to bitcast something that isn't a pointer. This is supported by LLVM just not by us right now.
- Add support for zero-alignment allocations.

Fix a few small issues

---

include/caffeine/IR/Assertion.h
include/caffeine/Memory/MemHeap.h
src/IR/Debug.cpp
src/Memory/Debug.cpp

As in title, these are provided to be useful while debugging or while adding print statements to the program.

Add debug printing methods to MemHeap and Assertion

---

include/caffeine/ADT/PersistentArray.h
src/IR/Debug.cpp

#267 broke the build on clang. This PR fixes it.
I'm going to add a follow-up PR to use clang in CI.

Fix broken clang build

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp

The fork API for context is rather inconvenient to work with. This PR changes it to return a vector of contexts so that it's not necessary distinguish between the current context and all the forks.
The old API is still available as `Context::fork_once` when that is more convenient.

Redesign context forking API

---

src/Interpreter/Interpreter.cpp

It's not used anymore so it should be deleted.

Delete WRAP_FUNC macro from Interpreter.cpp

---

include/caffeine/ADT/Span.h
src/ADT/Span.cpp

This functions similar to std::string_view or llvm::ArrayRef except that it's a non-const reference to the underlying array.
This will be used in some following PRs. The implementation is simple enough that I figure that it doesn't really need any tests.

Introduce Span ADT

---

include/caffeine/ADT/Guard.h
include/caffeine/ADT/SlotMap.h

This takes the `drop_guard` type from `SlotMap.h`, renames it to `ScopeGuard` and moves it to its own header so that it can be more broadly used.
I've also added a `dismiss` method since that's present in folly's version and I found it to be quite useful on occasion.

Move ScopeGuard from SlotMap.h into its own header

---

src/Interpreter/PrintingFailureLogger.cpp

This makes interpreting why something failed a lot easier (assuming that the log_failure call was annotated with a failure message).

Make PrintingFailureLogger print failure reason if one is present

---

src/Interpreter/Interpreter.cpp

LLVM has a similar utility function available as `llvm::zip`. It works better too.

Delete zip function within Interpreter.cpp

---

CMakeLists.txt
cmake/CaffeineTestUtils.cmake
cmake/LLVMIRUtils.cmake

In the previous setup clang would generate a depfile with the dependencies specified using absolute paths. However, ninja expects
the depfile target path to be relative to the binary directory. To fix this we need to update both the WORKING_DIRECTORY and the output filename for the compilation commands.
As an extra bonus, this also sets a property to disable useless "Built target X" messages when building using makefiles.

Fix bad depfile generation when building LLVM IR libraries

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/Policy.h
src/Interpreter/Interpreter.cpp
src/Interpreter/Policy.cpp

This is meant to be an interface that controls the behaviour of an Interpreter instance as well as providing a number of callback hooks. Currently not used anywhere, will be used in follow-up PRs.

Introduce ExecutionPolicy interface

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/Store.h
src/Interpreter/Interpreter.cpp
src/Interpreter/Store.cpp

This is meant to be a generalized interface to store/retrieve `Context` instances as needed for running interpreters.
The `ExecutionContextStore` is meant to manage:
- Prioritizing which contexts to run first and which to run later or never
- Blocking executor threads until a context is ready
I've also included an implementation of a threadsafe queue store that will serve up contexts to executors until all executors are blocked at which point it will return `std::nullopt`.
This isn't used yet but will be used in following PRs.
/stack #284

Introduce ExecutionContextStore interface

---

include/caffeine/Interpreter/Executor.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/Policy.h
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp
src/bin/caffeine.cpp

This adds two different interfaces that control queuing behaviour of the interpreter/executor:
- `ExecutionContextStore`: A store of `Context` instances that are not currently being executed. `add_context` adds a context to the store and `next_context` retrieves new ones back from the store.
- `ExecutionPolicy`: Indicates whether a given `Context` instance should be put in the queue or whether it should just be ignored. Also has several context lifecycle events that can be used for tracking info.
This PR is still a bit of a mess but the rest is too much effort to be pulled apart so leaving it as is.
/stack #285

Extract interpreter control behaviour into separate interfaces

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Memory/MemHeap.h
include/caffeine/Solver/Solver.h
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
src/bin/caffeine.cpp
test/unit/Memory/MemHeap.cpp

This PR breaks out the `Solver` from the `Context`. This is helpful in order to allow multiple `Solver`s to coexist in a multithreaded environment. As part of this change, the `Interpreter` now creates the `Solver` stack, as opposed to the caffeine binary harness. This is to allow each `Interpreter` to own it's `Solver` so that we can have a `Solver` per thread. Previously, it was only possible to have one `Solver` per runtime.
I was considering adding a method to `Context` along the lines of `setSolver` but decided against it because of the ownership issue.

Break `Solver` out of `Context`

---

src/Interpreter/PrintingFailureLogger.cpp

Found this way easier to use when debugging. Also the previous version was printing the hex nybbles backwards.

Change PrintingFailureLogger to print escaped ASCII strings

---

cmake/CaffeineTestUtils.cmake
tools/gen-test-main/main.cpp

I found this class while looking around at some LLVM tutorials. Since it's likely I'm going to be using it in the future I decided to learn how to use it by cleaning up the `gen-target-main` executable.
I've also bundled a dependency fix so changing `gen-target-main` rebuilds all the dependent files that use it in a build step.

Simplify gen-test-main using llvm::IRBuilder

---

.github/workflows/build-project.yml
CMakeLists.txt
cmake/CaffeineSanitizers.cmake

This adds some easy options to build caffeine + tests with sanitizers enabled.
I've enabled UBSAN in CI here. Will do a follow-up PR to enable ASAN once we can actually run without ASAN issues.

Add cmake options to build with sanitizers

---

cmake/CaffeineTestUtils.cmake
tools/gen-test-main/CMakeLists.txt

I'm planning on making some changes to this code here so this PR just reorganizes the cmake code here to be a little more sane. It also puts generated artifacts in more consistent directories which is helpful if you need to look at the build output.

Extract repetitive parts of CaffeineTestUtils to utility function

---

tools/CMakeLists.txt
tools/gen-builtins/CMakeLists.txt
tools/gen-builtins/builtins.h
tools/gen-builtins/main.cpp
tools/gen-builtins/memset.cpp
tools/gen-builtins/resolve.cpp

The current state of the repo is that we have builtin implementations for the most common calls to the `llvm.memset.*` intrinsic. Namely, we really only support the 
```
void llvm.memset.p0i8.i64(i8* %dst, i8 %val, i64 %len, i1 %isvolatile)
```
variant. This is done by hand-implementing a function
```
void caffeine_builtin_memset(...)
```
with the same signature in _LLVM IR_ and then having the interpreter patch calls to the intrinsic to instead point to the function we implemented by hand.
This has some big limitations:
1. We don't support anything other than the most basic memset calls. Anything that gets generated to use a different type will fail to compile. As an example, this will fail on platforms where pointers are 32-bits in size.
2. We don't support any platform that is not …

Introduce tool to generate implementations of LLVM builtins

---

cmake/CaffeineTestUtils.cmake
test/run-pass/mem/memset.c

Now that #294 has added a tool to generate implementations of the `memset` intrinsic this PR runs `gen-builtins` over test case IR files at build time so that they can take advantage of the new implementations.
This is part of the work towards resolving #293.
/stack #294

Generate implementations of `llvm.memset.*` intrinsic as part of the build process

---

cmake/CaffeineTestUtils.cmake
test/run-pass/mem/memset.c
tools/gen-builtins/CMakeLists.txt
tools/gen-builtins/assert.cpp
tools/gen-builtins/builtins.h
tools/gen-builtins/main.cpp
tools/gen-builtins/memcpy.cpp
tools/gen-builtins/resolve.cpp

This extends the support for generating builtins in #294 to also support `llvm.memcpy`. See the comment within the file for details on what actually gets generated.
Note that we can't delete `caffeine_builtin_memcpy` yet since it's still used by `memmove`.
/stack #297 
This is part of the work towards addressing #293

Add support for `llvm.memcpy` to gen-builtins

---

.github/workflows/build-project.yml

Stackbot branches are always identical to the head of a PR branch. There's no point in building them in CI since that's already being covered by the PR build.

Avoid running CI on stackbot branches

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

Now that everything is being handled through `OpRef`s (which are `const`) these non-`const` methods are no longer useful. Moreover, they constrain possible implementations so it's better just to get rid of them.
This also rewrites the operand iterator to not assume that the underlying representation of operands is linear in memory.
The reason for this PR is twofold
1. I'm trying to replace `PersistentArray` with an external library, and the non-`const` methods are blocking this
2. They're dead code that we're not intending to use, they should just be deleted.

Remove all non-const methods from all operation types

---

CMakeLists.txt
cmake/CaffeineTestUtils.cmake

This should be the last bit needed to get caffeine to compile (although not with all the tests) on windows.

Add cmake option to disable IR tests

---

cmake/CaffeineDependencies.cmake
cmake/CaffeineTemplateCMakeLists.txt.in
src/CMakeLists.txt

This PR rewrites `CaffeineDependencies.cmake` to build dependencies outside the project. Here's some stuff quoted from the commit message to explain what's going on (check out the commit message for the full explanation):
> At the moment, FetchContent will always add the fetched depenency as a subdirectory. This works ok if the dependency's CMakeLists is written to work properly when added as a subdirectory. Unfortunately, the CMake configurations for most projects are... not. This limits the number of dependencies that we can bundle using FetchContent to only a few.
> 
> However, cmake does already have support for doing all the difficult bits of bundling dependencies by using ExternalProject_Add. Unfortunately this doesn't help us directly as ExternalProject_Add is targetted towards …

Build packaged dependencies as external projects

---

cmake/CaffeineFormatting.cmake
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
tools/gen-builtins/memcpy.cpp
tools/gen-builtins/memset.cpp

This hasn't been working for a little while. Turns out we were diffing against the wrong files. I've also formatted everything here.
This should hopefully mean that CI starts properly checking formatting again.

Fix the `check-format` target

---

.github/workflows/build-project.yml

We no longer have any memory leaks. This means that we can enable ASAN in CI. This PR does so.

Enable ASAN in CI

---

cmake/CaffeineTestUtils.cmake
src/bin/caffeine.cpp
test/regression/CMakeLists.txt
test/run-fail/CMakeLists.txt
test/run-pass/CMakeLists.txt

Currently, we call `std::abort` if we fail to parse one the input files to `caffeine-bin`. This is done so that the run-fail tests fail if we fail to parse the file even though the `WILL_FAIL` property is set to true.
This PR adds a new flag `--invert-exitcode` to caffeine bin which flips the exit code for failures (e.g. 0 on failure found, 1 otherwise) but keeps the other error cases as their original exit codes. I've then gone and changed the test cases to take advantage of this.

Add `--invert-exitcode` option to `caffeine-bin` and use it for tests

---

src/IR/Operation.h
test/unit/IR/Matching.cpp

Previously this was done as part of the simplify transform. However, it doesn't require any special context so this moves it be done as part of operation creation.
/stack #322

Add automatic simplification of `Not(Not(x))` expressions

---

include/caffeine/ADT/SparseVector.h
src/IR/Operation.h
test/unit/ADT/SparseVector.cpp
test/unit/IR/Matching.cpp

This is vector which can have holes where elements might be. This allows us to erase elements while iterating over the same vector which is useful for transforms that will be applied to the list of assertions.
/stack #323

Implement new `SparseVector` data structure

---

src/CMakeLists.txt
src/Support/CMakeLists.txt
tools/gen-builtins/CMakeLists.txt

Currently `gen-builtins` gets rebuilt whenever we touch anything within caffeine. This is annoying since it causes all the IR files to get rebuilt. This PR changes it to only depend on the assert code so that it doesn't get rebuilt every time.

Make `gen-builtins` only depend on `caffeine-assert` target

---

include/caffeine/Interpreter/AssertionList.h
src/Interpreter/AssertionList.cpp
test/unit/Interpreter/AssertionList.cpp

This is meant to be a dedicated data structure for handling lists of assertions. It separates assertions into known-SAT and unproven assertions. This allows for transforms and various solvers to be done incrementally. Furthermore, `AssertionList` automatically breaks down top level and-expressions (list `DecompositionSolver`). See the comment at the top of `AssertionList` for a better explanation.
In the next set of PRs I will convert the rest of the code to use `AssertionList`.
/stack #324

Introduce new `AssertionList` data structure

---

test/unit/ADT/SparseVector.cpp

This testcase documents the behaviour of invalid access for the `SparseArray`

Add small testcase for invalid access of `SparseArray`

---

include/caffeine/IR/Operation.h
src/IR/Operation.cpp
src/IR/Operation.h

This PR adds code to transparently intern operation references at creation time. It does this by maintaining a global map containing `weak_ptr`s to all `Operation` instances. This allows it to transparently reuse operation instances while they are being created.
This can then be reused by downstream systems to efficiently deduplicate expressions.

Add transparent interning for operations

---

include/caffeine/Interpreter/Context.h
include/caffeine/Memory/MemHeap.h
src/Interpreter/Context.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
src/Solver/Z3Solver.cpp

As in title. This prevents us from having to resolve the same pointer over and over again for repeated memory accesses.
As a bonus, I've also added an early-exit if `extra` is false within the Z3 solver.

Propagate pointer resolutions back into other equivalent pointers in the stack frame

---

include/caffeine/Solver/Z3Solver.h
src/Interpreter/Context.cpp
src/Solver/Z3Solver.cpp

This takes advantage of the features of `AssertionList` to avoid performing solver queries if not necessary.
Closes #320

Take advantage of `AssertionList` features

---

tools/CMakeLists.txt
tools/guided-fuzzing/CMakeLists.txt
tools/guided-fuzzing/include/GuidedExecutionPolicy.h
tools/guided-fuzzing/src/GuidedExecutionPolicy.cpp

This PR adds a `GuidedExecutionPolicy` class. The purpose of this class will be to load it with assertions in order to only allow execution of paths that fit a given concrete input to a function.

Add GuidedExecutionPolicy

---

src/bin/caffeine.cpp

As in title. `-t <n>` means use `n` threads and 0 means to use the number of CPU cores.

Add flag to specify the number of threads used

---

include/caffeine/Interpreter/Interpreter.h
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp

Creating a Z3 context is very expensive. It can also be reused with multiple Z3 solvers without any issues.
This commit gives a 100x performance boost by reusing the solver stack for every context in a thread.
This is part of #335

Limit solvers to 1-per-thread

---

CMakeLists.txt
cmake/CaffeineFlags.cmake

As in title. This is needed so that `perf record` actually records complete call stacks.

Specify -fno-omit-frame-pointer for RelWithDebInfo build type

---

.github/scripts/setup-env.sh
.github/workflows/build-project.yml

As in title. This should ensure that branch protection sticks around when we want to change things.

Use a script in CI to simplify the build matrix

---

cmake/CaffeineLinking.cmake
cmake/LLVMIRUtils.cmake
scripts/gen-yarpgen-tests.sh
tools/gen-builtins/memcpy.cpp
tools/gen-builtins/memset.cpp

There are two main changes here:
- `llvm_library` now automatically runs `gen-builtins` over the generated library. This is fine since `gen-builtins` is idempotent
- Fix the `gen-yarpgen-tests.sh` script to work with the new `llvm_library` cmake code. (also make it executable)
- Edit: turns out that the generated builtin functions had problems if contained in multiple modules. I've changed the linkage to be `linkonce` so that everything works (multiple definitions will be merged together).

Fix script to generate yarpgen tests

---

CMakeLists.txt
cmake/AFLplusplus.patch
cmake/CaffeineDependencies.cmake
tools/guided-fuzzing/CMakeLists.txt
tools/guided-fuzzing/src/SymbolicMutator.cpp

This PR fixes a bug where empty strings cannot be passed to the `caffeine_dependency` rule and also adds AFL++ to the symbolic mutator / guided fuzzing tool.

Add AFLplusplus for symbolic mutator

---

include/caffeine/Interpreter/Context.h
src/Interpreter/ContextBacktrace.cpp

This implements a detailed backtrace printer for printing the call stack of the program being executed. If the information is available it will try to print as much context info as possible. However, I've tried to write it to still work acceptably and not crash even if the context is quite broken as this is intended to be used within a custom assertion type I'll be introducing in the next few PRs.
An example backtrace  is:
```
#0 test
| store i32 0, i32* %2, align 4, !tbaa !2
#1 main
| call void @test()
```

Implement backtrace printer for Context

---

include/caffeine/Interpreter/Context.h
src/Interpreter/ContextBacktrace.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/bin/caffeine.cpp

This also makes it work when passed a non-SAT model (this isn't great but it's currently the best way to indicate a internal error).
/stack #354

Use new backtrace support within `PrintingFailureLogger`

---

include/caffeine/Support/UnsupportedOperation.h
src/Interpreter/Executor.cpp
src/Interpreter/ExprEval.cpp
src/Support/UnsupportedOperation.cpp

This PR allows for caffeine to recover from running into an unsupported LLVM operation by killing the currently executing context. To do this it introduces two new assertion/abort macros:
- `CAFFEINE_UNSUPPORTED(message)`, and
- `CAFFEINE_UASSERT(cond, message)`
These behave like `CAFFEINE_ABORT` and `CAFFEINE_ASSERT`, respectively, but instead of aborting the whole process will instead (depending on configuration) throw an exception that gets caught within executor. This means that we end up killing the context but not the whole process, allowing other contexts to continue executing. Since we know that things aren't entirely broken we also have the ability to do things like print out a nice call stack of the current context.
/stack #354

Add support for recovering from an unimplemented feature

---

cmake/LLVMIRUtils.cmake
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/Interpreter.cpp

There's nothing special that caffeine needs to do to support debug info, we just have to ignore it. This PR does just that. I've also enabled debug info in all tests so that when #354 gets merged it'll also show the source lines (where applicable).

Add support for debug info

---

include/caffeine/Interpreter/ExprEval.h
src/Interpreter/ExprEval.cpp
test/regression/issue-359.pass.pointer-select.c

Within caffeine pointers are stored within the `Pointer` type. However, when executing a `select` instruction `ExprEvaluator::visitSelectInst` would return a non-pointer expression. This broke assumptions of later instructions and resulted in assertion failures.
This PR fixes this problem by changing `visitSelectInst` to return a pointer if either of the operands are pointers. I've checked the other methods in `ExprEvaluator` and I didn't see anywhere else where this could happen. (The only other case I could think of was the vector instructions but apparently vectors of pointers aren't allowed).

Fix `select` operation for pointer types

---

cmake/CaffeinePatch.cmake

The current one fails when a new file has been added since `git reset --hard` doesn't remove those fails. This fixes that by also running `git clean` to remove untracked files.

Implement more robust patching script

---

src/Solver/Z3Solver.cpp
test/regression/issue-361.pass.zext-bool.ll

This PR fixes a bug where caffeine will crash when `Z3Solver` attempts to build a `zext` operation for an inner type which is actually represented using a boolean. See the commit messages for a more detailed description of the bug. I've included a test case to ensure that the issue doesn't crop up again.
Closes #361

Fix zext bug within `Z3Solver`

---

include/caffeine/IR/Operation.h
include/caffeine/Interpreter/AssertionList.h
include/caffeine/Solver/Solver.h
src/Interpreter/Debug.cpp
src/Solver/Solver.cpp

This PR adds three things:
- A `DebugPrint` method on AssertionList
- A `operator<<` method on `SolverResult`
- `Operation::DebugPrint` is now public
These were both useful while debugging.

Various debug output cleanups

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/ExprEval.h
include/caffeine/Interpreter/StackFrame.h
include/caffeine/Memory/MemHeap.h
include/caffeine/Solver/Solver.h
src/Interpreter/Context.cpp
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
test/unit/Memory/MemHeap.cpp

This PR adds support for multiple distinct heaps being used at the same time. This is intended to support the following features:
- LLVM address spaces, where pointers to different heaps don't interact
- A separate function heap, as used in #367 
It does this by introducing a new type, `MemHeapMgr`, which is responsible for mapping heap IDs to the actual heaps. To make things easier it also provides helpers for some methods on `MemHeap` which forward to the correct heap based on the stored heap ID within the pointer. I've then gone through and updated all the locations which interacted with the heap to now work with the correctly-indexed heap (mainly by selecting by either the heap of the existing pointer or via the address space of the LLVM pointer it represents).
/stack #356

Implement support for multiple heaps

---

include/caffeine/Support/Signal.h
include/caffeine/Support/UnsupportedOperation.h
src/Interpreter/Executor.cpp
src/Solver/Z3Solver.cpp
src/Support/Signal.cpp
src/bin/caffeine.cpp
test/unit/main.cpp

This PR simplifies the printing of error messages to better take advantage of what LLVM offers. Here's what's included in this PR
1. Strip out terminate and signal handlers that duplicate functionality from LLVM
2. Print out a symbolic backtrace if we're currently within a context
3. Attempt to prevent Z3 from registering it's own signal handler
This PR still hasn't quite solved how to get `SIGINT` handling working correctly but I don't think that's a huge issue at the moment.

Simplify signal handling and print symbolic call stack on signal

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Value.h
src/IR/Operation.cpp
src/IR/Operation.h
src/IR/Value.cpp
test/unit/IR/Operation.cpp
test/unit/IR/Value.cpp

This can happen with a concrete allocator when the alignment of the allocation is 0. To avoid having this issue I've changed the `Value` operations to have valid, if somewhat arbitrary, values when calculating the remainder and then changed the const folding code to use them when applicable.
I've also added some test cases that cover this issue.

Avoid causing segfaults when constant folding divide-by-0 expressions

---

src/IR/Operation.h

If we have an operation like `(select cond x x)` then it will always return `x` and so we can simplify it to just `x`. This change does so.

Simplify select operations where both conditions are identical

---

src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
tools/opt-plugin/test-main/plugin.cpp

In this case we already know exactly what value the global will have so there's no need to go an evaluate each sub-expression since we know the final result will just be zeroed memory.
This also fixes an issue where allocations would be 8 times larger than they needed to be (due to using size in bits instead of size in bytes) as well as an issue where the pass to generate `main` for test cases was not nul-terminating strings.

Simplify evaluation of zeroinitializer globals

---

include/caffeine/ADT/SparseVector.h
include/caffeine/Interpreter/AssertionList.h
src/Interpreter/AssertionList.cpp
src/Solver/Z3Solver.cpp
test/unit/Interpreter/AssertionList.cpp

This PR adds two helper functions to `AssertionList`.
- `checkpoint` returns a value that can be then fed into
- `restore` which removes all values that have been inserted into the list since the corresponding `checkpoint` call.
This is useful as a general "insert things into the list to see if they're already present" strategy. In this PR, I've used it to simplify `Z3Solver`.
At the same time I ran into bugs in `AssertionList` and `SparseVector` since checkpointing/restoring results in them being in new states. I've included fixes and a test case in this PR as well.

Add the ability to checkpoint and restore an `AssertionList`.

---

include/caffeine/ADT/Guard.h

This gives a more accurate stack trace when an exception gets thrown as part of the guard destructor.

Mark Guard destructor as `noexcept(false)`

---

include/caffeine/Solver/Z3Solver.h
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

As it turns out, constructing a z3::tactic is rather expensive. Tracing data shows it as taking ~100ms each and every time we do it. This commit creates exactly one tactic at startup and then uses it to create all of the solvers later on.
Some basic benchmarking shows a 25% improvement on the `bench-maze` benchmark.

Construct z3::tactic at solver creation time

---

include/caffeine/IR/Type.h
include/caffeine/Interpreter/Context.h
src/IR/Type.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/Memory/MemHeap.cpp
src/Solver/Solver.cpp

Currently, we use a symbolic array to represent the arrays emitted `caffeine_make_symbolic`. This is quite slow. This PR replaces this with allocating a `FixedArray` of byte constants. To make this work, I've changed `Context` to have a map of symbol names to constant values.
This change improves the peformance on the `maze-symbolic` benchmark by at least 100x. I haven't actually had the time to run that benchmark to completion on the old version of the code so it might be more.
- Change `Model::evaluate` to automatically decide the values of constants that are not mentioned in the model (these are ones where we don't care about their value).
- Change `PrintingFailureLogger` to directly use the new way of exposing named constants.
- Add a map of string constant names -> expressions for …

Optimize constant-size symbolic arrays

---

include/caffeine/IR/Operation.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
test/unit/Memory/MemHeap.cpp

This was something that LLVM has for `ICmpInst` and I found it quite useful. This PR does the same and then replaces all the cases where it could be used.

Implement helpers for creating ICmpOp instances with a specific comparison

---

CMakeLists.txt

This PR does two things:
1. Explicitly search for LLVM 11.1 to see if it's available
2. Silence a warning that pops up in cmake 3.20 but doesn't affect us

Fix build on systems with LLVM 11.1

---

CMakeLists.txt
bench/CMakeLists.txt
bench/maze-symbolic.c
bench/maze.c
cmake/CaffeineTestUtils.cmake
cmake/LLVMIRUtils.cmake
tools/opt-plugin/builtins/memcpy.cpp
tools/opt-plugin/test-main/plugin.cpp

This PR adds a `bench` folder along with two benchmarks lifted out of a KLEE tutorial. The two benchmarks added right now are
1. The maze example from the KLEE tutorial. This benchmark is composed mainly of concrete variables with the exception of the input. Currently this takes 1m 23s of total CPU time.
2. A symbolic version of the maze example. This benchmark makes everything symbolic. This benchmark currently takes > 1h 45m of total CPU time (I didn't wait to see how long it would take)
If you read the examples closely you'll note that there's a bug in the maze algorithm. This means that there are multiple possible paths through the maze. I've also cleaned up the internal cmake setup somewhat.
This is part of #335 and closes #203. Feel free to suggest more benchmarks you think we …

Add some simple benchmarks 

---

Dockerfile
include/caffeine/Memory/MemHeap.h

The docker build already runs as root so there's no point in using `sudo`.
In fact, doing so is an error.
Also fixes some minor typos.

Fix docker build

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/FailureLogger.h
include/caffeine/Solver/CanonicalizingSolver.h
include/caffeine/Solver/SequenceSolver.h
include/caffeine/Solver/SimplifyingSolver.h
include/caffeine/Solver/Solver.h
include/caffeine/Solver/Z3Solver.h
src/Interpreter/Context.cpp
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/PrintingFailureLogger.cpp
src/Solver/CanonicalizingSolver.cpp
src/Solver/SimplifyingSolver.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h
src/bin/caffeine.cpp
tools/guided-fuzzing/src/GuidedExecutionPolicy.cpp

One thing that's been bugging me for a while is that `Model` basically has two responsibilities: it's a result from a solver (e.g. SAT, UNSAT) and it's model that can be used to get concrete values for random expressions. These are distinct responsibilities. This PR is an attempt to change things so that responsibilities are distributed in a cleaner fashion.
This PR is meant to be an RFC. If we can think of a better way of refactoring things here then I'd love to hear about it so that I can implement it :)
The main new changes from this are
- `SolverResult` has been converted from an enum to a class. Logically, it is now a result from a solver with an optional model if it is `SAT`.
- `Model` is now just a model. It no longer has an associated solver result and is instead just responsible …

Rework solver API to split models from solver results

---

docs/notes/tracing.md

This is a supplemental addition to #387 that describes how to use the tracing code and open it up in the chrome trace viewer.

Add docs for how to do tracing

---

CMakeLists.txt
Config.h.in
include/caffeine/Support/Assert.h
include/caffeine/Support/Macros.h
include/caffeine/Support/Tracing.h
src/Protos/tracepoint.capnp
src/Solver/Z3Solver.cpp
src/Support/Tracing.cpp
src/bin/caffeine.cpp

This PR adds a small tracing library that can be used to log arbitrary spans while caffeine is running. This is meant to allow for easier performance analysis. I've already used it to diagnose one performance improvement (#386).
If disabled at compile time, the tracing support should optimize away to nothing. If not, it has to check one global variable to see if it's enabled. I've put the existing tools I've written to work with it [here](https://github.com/insufficiently-caffeinated/tracing-tools).
This required a few changes to more than just setting up tracing. Here are the detailed changes:
- We now have a config header that is configured based on cmake options passed to the cmake configure step. The template for this is `Config.h.in` in the root of the repo.
- There is now a …

Implement arbitrary tracing support

---

cmake/CaffeineDependencies.cmake

If you change the generator for the cmake build directory without deleting all the files in the build directory then you'd run into errors for the packages downloaded by caffeine_dependency as they would still be using the old generator. This fixes that by deleting them if the generator has changed since the last time cmake ran.
Ultimately, it's a pretty rare error so it doesn't matter too much if it gets fixed but it's the right thing to do.

Fix error when changing generators without removing all files

---

CMakeLists.txt
Dockerfile

This commit:
* Adds the QUIET flag to a find_package call in a cmake file because if
that call fails it's not an error
* Removes a redundant update-alternatives command which is performed as
a part of the previous build step

Improve cmake config and Dockerfile

---

cmake/CaffeineDependencies.cmake

As in title. Previously this caused a non-fatal error to be printed out on cmake versions older than 3.17.

Don't use cmake -E rm for older cmake versions

---

include/caffeine/Interpreter/Policy.h
src/Interpreter/Interpreter.cpp
src/Interpreter/Policy.cpp

This PR adds an optional Assertion to `ExecutionPolicy::on_path_complete`
which will allow us to simplify the error handling of Policies (making
use of the `logFailure` handler unnecessary).
Closes #401

Add optional extra Assertion to `on_path_complete`

---

CMakeLists.txt

As in title. This changes the test target to pass `jN` where `N` is the number of processors in the system. Note that this only happens on newer cmake versions which actually support adding extra arguments to the `test` target.

Have the `test` target run tests in parallel

---

include/caffeine/Interpreter/AssertionList.h
src/Interpreter/AssertionList.cpp

As in title. This is similar to the `unproven` accessor but it returns all the assertions that are proven.

Add `proven` accessor to AssertionList

---

include/caffeine/ADT/WeakMap.h
test/unit/ADT/WeakMap.cpp

This PR adds a new container `weak_map` that acts as an `std::unordered_map` with `std::weak_ptr` keys. That is, it's somewhat like a cache that automatically cleans up values when the corresponding `std::shared_ptr` key is deleted (eventually). I will be using this to implement caching within a new solver that will be introduced in the next set of PRs.
The code added here is pretty straightforward -- if somewhat verbose -- because it can forward to the underlying `std::unordered_map` for everything.

Implement `std::unordered_map` variant with `std::weak_ptr` keys

---

Dockerfile
README.md

Removed instances of `clang++-11` from the required packages since it's not a package ( [link](https://packages.ubuntu.com/focal-updates/) )

Correction to build instructions on Linux and Docker setup

---

include/caffeine/ADT/Span.h
include/caffeine/ADT/ThreadMap.h
include/caffeine/Interpreter/Store.h
src/Interpreter/Store.cpp
src/bin/caffeine.cpp

This PR adds an `ExecutionContextStore` which keeps a small thread-local cache of the most recent contexts that will be used first when `next_context` is called. This should hopefully allow the same context to continue to be executed by the same thread while still distributing work to others once there are a bunch of threads.

Implement context store with better cache locality

---

include/caffeine/Interpreter/ExprEval.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/Value.h
include/caffeine/Interpreter/Value.inl
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
test/run-pass/inst/extractvalue/nested.ll
test/run-pass/inst/extractvalue/roundtrip.ll

These instructions allow you to interact with literal struct fields within LLVM. They're not used by most code but code generated as a result of some builtins makes use of them.
- Implement `extractvalue`/`insertvalue` in `ExprEvaluator`
- Add non-const accessors to `LLVMValue` so that they can be used for `insertvalue`
- Add two test cases covering the easy case for the implementation

Implement `extractvalue` and `insertvalue` instructions

---

include/caffeine/IR/Operation.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Solver/Z3Solver.h
src/IR/Operation.cpp
src/IR/Operation.h
src/Interpreter/Interpreter.cpp
src/Interpreter/Interpreter/llvm.umul.with.overflow.cpp
src/Solver/Z3Solver.cpp
test/run-pass/intrin/umul.with.overflow/check-oversized-ints.c
test/unit/IR/Operation.cpp

As in title. As any test case that's going to use this will involve the `extractvalue` instruction I'm stacking it on top of #417. Since `Interpreter.cpp` is getting large I've decided to put the implementation for this method into it's own file. I've also added a test case that verifies some of the behaviour.
The implementation of overflow checking is based of the technique described in the paper [here](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.37.4513&rep=rep1&type=pdf). It is a similar technique to what Z3 uses. I did this to avoid having to introduce a new opcode. I've included a test case showing that it is equivalent to the version Z3 has which should be enough to show that it is correct.
/stack #417
Closes #337

Implement `llvm.umul.with.overflow` intrinsic

---

include/caffeine/IR/Operation.h
include/caffeine/Interpreter/Interpreter.h
src/IR/Operation.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/Interpreter/llvm.smul.with.overflow.cpp
test/unit/IR/Operation.cpp

As in title. This is pretty similar to the `llvm.umul.with.overflow` intrinsic and the actual bitwise logic used to calculate it is pulled from the same paper as with the unsigned version.
/stack #418 
Closes #414

Implement `llvm.smul.with.overflow` intrinsic

---

cmake/CaffeineTestUtils.cmake
include/caffeine/Interpreter/Context.h
scripts/gen-yarpgen-tests.sh
src/Interpreter/Context.cpp
tools/caffeine/main.cpp

Previously the entry point was a mandatory positional argument. However, we almost always want to use `main` as the entry point so it doesn't make sense for it to be a required argument. This PR changes it to be a flag `--entry` with the default value of `main`.
I've also removed the code that will automatically generate symbolic constants for the arguments of the entry point method. I have, however, left the special casing for `main` so that existing tests continue to work.

Change command line entry point to no longer be a mandatory argument

---

bench/CMakeLists.txt
cmake/CaffeineTestUtils.cmake
cmake/CaffeineUtils.cmake
cmake/LLVMIRUtils.cmake

The problem was that file dependencies can be duplicated by the makefile generator. The solution is to wrap the files generated by add_custom_command calls with a custom target so that they don't get duplicated when cmake generates the makefiles.
The solution and problem explanation can be found on this blog post: https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/
Closes #404

Fix race condition for makefile builds

---

.github/workflows/find-coverage.yml
cmake/CaffeineTestUtils.cmake
test/unit/CMakeLists.txt

Previously the generated `default.profraw` file for all the test cases would all overwrite each other when being executed. In larger parallel builds this usually led to corrupted coverage info. Even if it worked it would result in the reports missing data for the other test cases.
This fixes that by doing a couple of different things:
1. When coverage is enabled we run caffeine-unittest all at once instead of generating a different cmake test case for each contained test.
2. We use the `LLVM_PROFDATA_FILE` env var to make the run-file tests generate their profiling data with a different filename for  test.
There's still some holes in this (googletest death tests don't properly generate coverage at the moment) but it should be better than the status quo.

Fix some issues with test coverage generation

---

include/caffeine/ADT/Span.h
tools/guided-fuzzing/include/CaffeineMutator.h
tools/guided-fuzzing/include/GuidedExecutionPolicy.h
tools/guided-fuzzing/src/CaffeineMutator.cpp
tools/guided-fuzzing/src/GuidedExecutionPolicy.cpp
tools/guided-fuzzing/src/SymbolicMutator.cpp

I spent at least 6 hours debugging why this didn't work only to discover it was mainly due to different optimization settings when building the test case. However I also made a bunch of changes that I felt were worth having.
- Add conversions between `Span` and `std::string_view`. (not really a part of the change but I don't really want to make a separate PR for this)
- Test cases are now stored as `std::string` instances instead of `SharedArray`
- There is now a separate entry point `__caffeine_entry_point` instead of calling `main`.  This allows us to set the size of the symbolic constant appropriately without having to resort to a symbolic size. It also means that it should be able to be linked into a real program without too much of an issue.
- Put the slicing solver into the solver …

Various fixups to afl-guided-mutator

---

src/IR/Operation.cpp
test/unit/IR/Operation.cpp
test/unit/IR/Value.cpp

This PR adds more tests to cover `Operation.cpp`
Closes #427

Cover more of `Operation.cpp` and `Value.cpp`

---

include/caffeine/Interpreter/ExprEval.h
src/IR/Operation.cpp
src/Interpreter/ExprEval.cpp
test/run-pass/inst/extractelement/extract-ptr-vector.ll
test/run-pass/inst/insertelement/insert-ptr-vector.ll

Basically these instructions caused crashes when used on vectors of pointers. This was discovered when trying to write a test case for #432. I've also included a better assertion message for some assertions in `Operation.cpp`.
This includes test cases for both error cases.
Closes #433

Fix `insertelement` and `extractelement` instructions on vectors of pointers

---

cmake/CaffeineTestUtils.cmake
cmake/LLVMIRUtils.cmake

These were broken again 😦. This PR fixes the dependencies yet again.
Eventually I should create a cmake library that fixes this bs...

Fix dependencies for test case build

---

include/caffeine/Support/Tracing.h
src/Support/Tracing.cpp

This is just another small set of optimizations to avoid running code when tracing is disabled.

Avoid evaluating trace span names if tracing is disabled

---

test/unit/Interpreter/ExprEval.cpp

These are the lines that keep showing as a coverage reduction. It's not really a useful test it just means that there should be fewer spurious coverage warnings (hopefully)

Add a test covering the assertion in ExprEval

---

src/Interpreter/ExprEval.cpp
src/Support/Tracing.cpp
test/run-pass/inst/getelementptr/vector-gep.ll

There's a number of GEP variants that can show up. We crash on most of the vector ones. This PR fixes that and adds test cases that cover the new branches.
Closes #432
/stack #437

Fix vector `getelementptr` instructions

---

CMakeLists.txt
Config.h.in
cmake/CaffeineConfig.cmake.in
src/CMakeLists.txt

As in title. This allows us to run `make install` to install caffeine and then other projects can use `find_package(caffeine)` to make use of caffeine. The current targets that are included are
- `caffeine`
- `caffeine-opt-plugin`
- `caffeine-bin`
- All public headers (ones in `include` and generated ones)
- The builtins and libc bitcode libraries
- vcpkg triplet files
I haven't included the afl mutator since it doesn't match the naming conventions (it should be named caffeine-... so that it doesn't conflict with other libraries under `lib`)
I'm still not quite sure how to expose bitcode libraries. For the moment I've elected to just put them under `lib/caffeine` and add some variables that have the file names.

Add install targets for caffeine

---

include/caffeine/IR/Operation.h
src/IR/Operation.cpp
src/IR/Operation.h
test/unit/IR/Operation.cpp

When we store a value to memory we first have to break it down into bytes. When we load it back again we then need to rebuild the value from the original bytes. This produces a large expression to effectively just go in a circle. This PR adds a number of simplifications that completely eliminate this type of expression.
This should hopefully simplify symbolic expressions by quite a bit when they have to go through memory.

Add simplifications to optimize away load-store cycles

---

src/Support/Signal.cpp

As in title. This should help track down errors in larger programs.

Print symbolic backtrace within signal handler

---

CMakeLists.txt
Config.h.in
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp

This adds tracing that tracks each individual executed instruction. It also adds an `CAFFEINE_TRACING_EXPENSIVE_ANNOTATIONS` config option which is used to enable/disable printing the resulting expression from instructions when they have one.

Add trace spans for individual instructions

---

src/IR/Operation.cpp
src/IR/Operation.h
src/Memory/MemHeap.cpp
test/regression/issue-362.pass.load-bool-from-memory.c

The issue was that if we are loading a type that takes up 1 byte in memory then we'd just directly forward the byte even if it was not valid to forward the byte. (e.g. if we're loading an i1 from memory then we'd just return an i8). This caused assertions later on when things were not as expected.
The fix is to only directly return the memory byte when the expected type is actually an i8, otherwise we need to go through the whole truncation/extension process.
Closes #362

Fix assertion when loading a boolean from memory

---

tools/guided-fuzzing/include/CaffeineMutator.h
tools/guided-fuzzing/src/CaffeineMutator.cpp
tools/guided-fuzzing/src/GuidedExecutionPolicy.cpp

This PR adds a default implementation of `__caffeine_entry_point` in case the user program does not provide it. Essentially, it adds
```
void __caffeine_entry_point(int size) {
uint8_t data[size] = {0};
caffeine_make_symbolic(data, size, "__caffeine_mut");
LLVMFuzzerTestOneInput(data, size);
}
```
to the module.

Autogen `__caffeine_entry_point` for AFL++ mutator

---

src/Support/CMakeLists.txt

I was running into cmake issues due to it not being part of the set of installed libraries. Changing it to an object library seems to have fixed them.
We aren't interested in using the library as a static library anyway so this doesn't change anything else.

Change caffeine-assert library to an object library

---

include/caffeine/Support/LLVMFmt.h
src/Memory/Allocator.cpp

As in title. I've also gone and added a hexadecimal format specifier for APInts.

Improve logging message for invalid deallocations

---

cmake/CaffeineFlags.cmake
src/CMakeLists.txt

This was an issue for me when I switched to my laptop (was running into compilation errors). We don't use RTTI anywhere (no dynamic_cast or typeinfo) so this doesn't affect us.

Add -fno-rtti flags to be compatible with fno-rtti LLVM

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/TransformBuilder.h
include/caffeine/Memory/MemHeap.h
src/Interpreter/TransformBuilder.cpp
src/Memory/MemHeap.cpp

A lot of operations involve first performing an operation that could fork and then doing other things on all the resulting contexts. This ends up being very tedious to write (e.g. resolving a pointer requires ~50 LOC every time we want to do it). This PR adds a utility that handles tracking all the forks and executing a series of operations on them.
So far I've only added the operations that were used in implementing `setjmp` and `longjmp`. As more operations are needed then they can be added. In the meantime, they will all be wrappers around the `transform_fork` function so there's no functionality that couldn't be implemented manually.

Add utilities for implementing forking operations in builtins

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/Builtins/setjmp-longjmp.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp
test/run-pass/intrin/longjmp/setjmp-longjmp.c
test/run-pass/intrin/setjmp/setjmp-no-longjmp.c

As in title. See the comment within `setjmp-longjmp.cpp` for an explanation of how this all works.
- Add a global registry for builtin library functions. This is a step away from them all needing to be member functions of `Interpreter`.
- Add a frame ID to all stack frames so that we can search for them when doing a `longjmp`
- Implement `setjmp` and `longjmp`
/stack #456

Implement `setjmp` and `longjmp`

---

include/caffeine/Interpreter/ExprEval.h
include/caffeine/Memory/BumpAllocator.h
include/caffeine/Memory/MemHeap.h
src/Interpreter/ExprEval.cpp
src/Memory/BumpAllocator.cpp

The `BuddyAllocator` we use is broken. However, I have not been able to figure out what is actually going wrong with it since it doesn't show up under simple test programs. As a stopgap measure this PR replaces the buddy allocator with a simpler one that is (more) obviously correct.
I've also included a change to make exceptions thrown by `ExprEvaluator` recoverable. This means that they only kill the current branch instead of all of caffeine.

Replace broken BuddyAllocator with BumpAllocator

---

Dockerfile

These two dependencies are going to be useful to c++ support in our test
suite.

Add `go` and `gllvm` to Dockerfile

---

src/Interpreter/Interpreter.cpp
src/Solver/Z3Solver.cpp

From looking at traces, the most common callers of `Solver::check` turn out to be pointer resolution. However, when run with the concrete allocator we end up with two problems:
- Resolving a pointer (in store and load) always ends up forking the context, and
- We are making lots of solver calls that don't require instantiating the underlying solver since they contain terms which are just `false`.
This PR addresses both of those issues. The first by using transform builder, and the second by explicitly checking for `false` assertions within the input assertion list.

Various optimizations to pointer resolution

---

CMakeLists.txt
include/caffeine/ADT/ThreadMap.h
include/caffeine/Interpreter/Store.h
include/caffeine/Interpreter/ThreadQueueStore.h
include/caffeine/Support/Tracing.h
src/CMakeLists.txt
src/Interpreter/Store.cpp
src/Interpreter/ThreadQueueStore.cpp
src/Support/Tracing.cpp
tools/caffeine/main.cpp

Currently we use `QueueingContextStore` (or a variant thereof that caches the last value). However, this has a problem that if there isn't enough work to saturate all the worker threads then the unused threads will spend a bunch of their time bouncing through locks when new values are inserted into the queue. This results in caffeine using far more CPU than is useful. Furthermore, when new values are inserted generally a different thread will win the race to pull the context out of the store. This means that there is little cache locality when dealing with these contexts.
This PR introduces a new context store called `ThreadQueueContextStore` that keeps a separate deque for each thread. When a thread needs to get a new context it'll pull the most recent one off of it's own queue. If it …

Implement better multithreaded context store

---

.github/scripts/update-alternatives-llvm.sh
.github/workflows/build-apt.yml

This PR adds an additional actions workflow that doesn't use the docker image. Instead it
- Takes advantage of the pre-installed libraries already on the ubuntu-latest github actions image
- Should (maybe) cache the build directory for faster follow-on rebuilds
- Uses ninja to build in CI (no more nonsensical percentage markers)
- Should be at least 30s faster due to not having to download an entire OS
- Also caches the output build directory for (hopefully) faster rebuilds.
The combination of caching + apt dependencies looks like it is able to bring the build time down to 1-2 minutes for a cached build.

Add CI workflow that doesn't use the docker container

---

cmake/CaffeineDependencies.cmake
include/caffeine/IR/Operation.h
include/caffeine/IR/OperationCache.h
src/CMakeLists.txt
src/IR/Operation.cpp
src/IR/Operation.h
src/IR/OperationCache.cpp

This PR does a few things
1. Add a new dependency on https://github.com/Tessil/hopscotch-map which is a fast hashmap library.
2. Rework the existing operation cache to use a shared lock so that no threads get blocked if the operation is already in the cache.
3. Move the operation cache to its own public header.
4. Change the last few non-cached operation types to be fully cached now.
The one exception here is that `FixedArray` is still lazily cached (i.e. only cached when we need to build an operation that uses it directly). This is to avoid quadratic blowup when caching lots of temporary writes to an array.
This is part of a series of PRs cleaning up caffeine in preparation for focusing more on optimization.

Rework `Operation` cache to avoid blocking threads

---

include/caffeine/ADT/SetTrie.h
test/unit/ADT/SetTrie.cpp

This PR introduces a new data structure called a set-trie. It allows for efficiently checking whether another set is a superset of any set contained within the set-trie itself.
In the following PR this will be used to efficiently check whether a query is a superset of a known unsat core.

Implement data structure for performing subset queries

---

cmake/CaffeineLinting.cmake

When building with ninja clang-tidy doesn't think it's outputting to a terminal so it doesn't use any color in the output. This change fixes that by telling it to always use colour.

Ensure `clang-tidy` diagnostics use colour

---

libraries/builtins/threading.c
test/run-pass/pthread/pthread_once.c

C++ exception support calls `pthread_once` at some point which means
that we need to support a bare bones implementation.

Add `pthread_once`

---

include/caffeine/Memory/MemHeap.h
src/Interpreter/ExprEval.cpp
src/Memory/MemHeap.cpp

This PR changes the size of the allocations used by function pointers to be the number of instructions within the function. This is a pretty small change that doesn't affect much but it'll allow me to refer to jump targets in a uniform way (the pointer to an instruction is now just function ptr + index of instruction). This will be used when trying to fix #485.

Rework function pointers

---

src/IR/Operation.cpp
src/Support/UnsupportedOperation.cpp

This fixes two of the clang-tidy lint warnings. I haven't understood what the root problem is with the other warnings so I haven't fixed them here.

Fix some `clang-tidy` lint warnings

---

src/Interpreter/Builtins/setjmp-longjmp.cpp
test/run-fail/intrin/call-longjmp.ll
test/run-fail/intrin/invoke-longjmp.ll
test/run-pass/intrin/longjmp/invoke-longjmp.ll

The issue here was pretty simple. All this PR does is do the 1-line fix and re-enable the test cases.
Closes #485

Fix search for `longjmp` target

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/Builtins/setjmp-longjmp.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp

Because currently external functions cannot return values, or call other
functions, I needed to refactor how return values are passed to previous
stack frames.

Refactor `StackFrame` in order to simplify returning results

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/Interpreter.cpp
src/Interpreter/StackFrame.cpp

This PR adds external stack frames which will be used to track return and resume values for functions called by external functions. It also adds a utility method to setup and tear down external stack frames before / after a function is called from an external method.
I didn't tie this all together yet because in the `Context` we have a vector of `StackFrame`s. However, since `ExternalStackFrame` subclasses from `StackFrame` we cannot store it in the same vector. I think the solution will be to use smartpointers in the `Context` but didn't want to add such a big change in one PR.

Add external stackframe

---

include/caffeine/Interpreter/StackFrame.h
include/caffeine/Model/Value.h
include/caffeine/Model/Value.inl
include/caffeine/Solver/Solver.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Memory/MemHeap.cpp
src/Model/Value.cpp

I'd like to separate all the core data structures we use for caffeine out into a `Model` folder so that they don't get conflated with all the stuff around `Interpreter`. This change is the first step in doing that.

Refactor LLVMValue and LLVMScalar header into Model folder

---

.gitignore
bazel/bitcode.bzl
include/caffeine/Solver/LoggingSolver.h
scripts/output-path.sh
src/Solver/LoggingSolver.cpp
tools/caffeine/main.cpp

This PR adds some helpers that I found useful while attempting to debug the malloc-free issue. They aren't used anywhere but are useful to when you need logging output.
This PR includes:
- A script to print out the path to the output of a bazel targets. This is surprisingly annoying to get out of bazel so I've wrapped it in a script.
- A solver wrapper that logs all the assertions passed in along with the result output by the solver.
- A fix to the test harness so that it runs caffeine tests in single-threaded mode similar to how the cmake test setup does.

Add some utility classes and scripts for debugging

---

BUILD
bazel/compile-commands.bzl

This allows for you to run `bazel run //:compile-commands` and it will generate a `compile_commands.json` database for use with editors. This does the same thing as `./scripts/gen-comp-commands.sh` except it is more convenient to use.

Add `:compile-commands` as a bazel target

---

bazel/bitcode.bzl
test/BUILD
test/run-fail/intrin/BUILD
test/run-fail/mem/BUILD
test/run-pass/intrin/longjmp/BUILD
test/run-pass/mem/BUILD
test/skip-test-bazel.sh

This change makes the bazel CI run all currently passing tests and any newly introduced ones. In order to make CI pass I've explicitly marked the currently failing tests as skipped within the BUILD files.
I'll remove these tests from the skipped lists as they get fixed.

[bazel] Run most integration tests in CI

---

CMakeLists.txt

Previously this would say that `clang-format` was not found which is wrong and confusing. This fixes the error message to actually say to install clang-tidy.

Fix cmake error message if `clang-tidy` is not found

---

.github/workflows/bazel.yml

Currently every CI run by a PR uploads a new cache artifact. These are large and can push out the caches made by the master branch rather quickly. Instead, this new change only uploads a cache in a PR if it didn't get a cache hit.

Relieve cache pressure by reducing the number of caches uploaded by PRs

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/InterpreterContext.h
include/caffeine/Support/UnsupportedOperation.h
src/Interpreter/Executor.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

This PR introduces a new wrapper class around `Context` that provides a unified interface for tasks to interact with contexts. This is meant to simplify the implementation of the interpreter and clean up other things.

Introduce a new `InterpreterContext` wrapper class

---

.github/workflows/bazel.yml

The `format` job is still generating a large cache upload every time it is run. However, it can reuse the cache from the build job if at all possible. This change will prevent it from uploading a new cache artifact if it gets any cache hit and also makes it prefer the cache for the `build` job.

Avoid caching the format action if possible

---

test/unit/BUILD

Turns out bazel wasn't linking all the tests in. This change fixes that so that all of our unit tests are actually being run by bazel test.

Fix test build configuration to always run all tests

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

This PR converts all the easy cases within `Interpreter` to use `InterpreterContext` instead of directly mucking about within `Context`. It also adds new utility methods to `InterpreterContext` to provide functionality that wasn't already there.
As the next part of this PR stack I'll look into fixing some of the harder parts.

Convert `Interpreter` to use `InterpreterContext` in easy cases

---

.bazelrc
.github/workflows/bazel.yml
bazel/bitcode.bzl
test/run-fail/BUILD

Both `collatz` and `murmurhash3` take > 30s to run. They are still useful to have but it's probably not necessary to run them every time we want to run unit tests locally.
This change marks them as manual and changes CI to still run manual tests. This way they are still continuously tested but they don't slow down the edit loop when working locally.

Mark slow tests as manual tests within bazel

---

include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

As in title. It turns out that the main issue was that `visitIndirectCall` was creating a copy of the interpreter without also updating the `InterpreterContext` pointer. This fixes that and also puts the same shim used within `execute` in `visitIndirectCall`.
This should now be enough for us to convert function calls to use `InterpreterContext` in a peicemeal fashion.

Convert visitIndirectCall to use InterpreterContext

---

include/caffeine/Interpreter/ExternalFunction.h

This PR introduces the interface for an external function. @mishazharov I realize you were probably going to do this but I needed it now and figured I'd just add it instead of kludging around it not existing yet and having to fix it again later.
The interface itself is pretty simple: all it has is a `call` function that takes an `InterpreterContext` and the function arguments. That's it. That function then does whatever is needed to actually run the function which may include creating an external stack frame if necessary.

Write ExternalFunction interface

---

test/unit/BUILD
test/unit/Interpreter/ExprEval.cpp
test/unit/Support/UnsupportedOperation.cpp
test/unit/Util/CaptureOutput.cpp
test/unit/Util/CaptureOutput.h

Throwing UnsupportedOperation always writes directly to stderr. GoogleTest does not automatically catch this in the case where the test passes. Since the output is rather noisy then this makes trying to debug other test failures harder.
This commit addresses this by capturing stderr output to a file and then only printing that output to stderr if the test case fails. In cases where this doesn't work then we fail open and just allow printing to stderr.

Hide stderr output from tests that throw UnsupportedOperation exceptions

---

include/caffeine/ADT/StringMap.h
include/caffeine/Interpreter/CaffeineContext.h
src/Interpreter/CaffeineContext.cpp

This PR introduces `CaffeineContext` it stores all the miscellaneous global bits which are part of the interpreter. That includes the policy, the context store, the options, the solver builder, and the registry of external and intrinsic functions.
Currently this PR doesn't actually make anything else use the `CaffeineContext` or add any functions external functions to the default set. Follow-up PRs will go and add this.

Introduce `CaffeineContext` and builder

---

WORKSPACE

We don't actually need any of the LLVM backends so we can save some time by disabling as many as possible before LLVM stops compiling. Unfortunately, I wasn't able to disable all of them but this disables the X86 one and should cut down on a number of files that need to be built.
This is an intermediate step on the way to using a pre-built LLVM.

Only build LLVM with the X86 backend

---

include/caffeine/Interpreter/Store.h
src/Interpreter/Store/NullContextStore.cpp

Sometimes we need a store for a test but don't want to actually store anything in it. For this, the NullContextStore is a store which just drops all inserted contexts and never returns any when queried.
This is needed for some of the refactoring done to use CaffeineContext everywhere.
/stack #543

Add an empty context store for testing purposes

---

.mergify.yml

As in title, this should make searching easier.

Make mergify remove the ready-to-merge label after merging the PR

---

.bazelrc

Without this flag bazel will automatically use the existing `PATH`, `LD_LIBRARY_PATH`, and `TMPDIR` variables from the environment. Unfortunately, these change fairly often and whenever that happens bazel will throw out the entire cache and rebuild everything from scratch. This is bad. It takes forever and we'd like to not have that happen.
This commit enables the strict_action_env flag which uses a hardcoded built-in `PATH` (unless overidden via action_env) and leaves `TMPDIR` and `LD_LIBRARY_PATH` empty.

Add `--incompatible_strict_action_env` to `.bazelrc`

---

include/caffeine/Interpreter/Executor.h
include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/Executor.cpp
src/Interpreter/InterpreterContext.cpp
test/unit/Interpreter/InterpreterContext.cpp
tools/caffeine/main.cpp
tools/guided-fuzzing/include/GuidedExecutionPolicy.h
tools/guided-fuzzing/src/CaffeineMutator.cpp

This converts most of the structs that would take a policy or a store to now interact with a `CaffeineContext`. This is mostly a straightforward change that 1:1 replaces the existing pointers with accesses to `CaffeineContext`.

Convert various structs to use `CaffeineContext`

---

include/caffeine/ADT/StringMap.h
include/caffeine/Interpreter/ExternalFuncs/CaffeineAssert.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/CaffeineAssert.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

This is the next step towards using `CaffeineContext` everywhere. This PR just makes `Interpreter` attempt to find functions within `CaffeineContext` before running the hardcoded ones.
I've used `CaffeineAssert` as a demo since it was already used as an example of an external stack frame.

Use `CaffeineContext` for external functions and convert `CaffeineAssert` to an external function

---

test/regression/BUILD
test/tests.bzl

Currently the regression tests are not being run by bazel. This PR fixes that.

[bazel] Add targets for regression test cases

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/InterpreterContext.cpp
test/unit/Interpreter/InterpreterContext.cpp

This PR includes two new methods and a bugfix to `InterpreterContext`:
- The new methods are utilities for performing the correct jump when simulating a return from an external function that doesn't actually create a custom external stack frame. This is expected to be the majority of external functions so these should be fairly important utilities.
- The fix changes `interpreter:;getCurrentInstruction` to actually return the currently executing instruction instead of the one that is scheduled to execute next. When calling `getCurrentInstruction` this is usually what is actually wanted.

Add utilities for handling function returns to `InterpreterContext`

---

include/caffeine/Interpreter/ExternalFuncs/CaffeineAssume.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/CaffeineAssert.cpp
src/Interpreter/ExternalFuncs/CaffeineAssume.cpp
src/Interpreter/Interpreter.cpp
test/run-pass/intrin/caffeine_assert/BUILD
test/run-pass/intrin/caffeine_assert/invoke-assert.ll

This PR does 3 main things:
- The biggest one is the one from the title: convert `caffeine_assume` to be an external function that derives from `ExternalFunction` and is included in the default external function map.
- Beyond that, I've also introduced a test case to verify that invoking `caffeine_assert` works as expected.
- Finally, it includes a small fix to `caffeine_assert` to ensure that when it is invoked it returns to the right location.
/stack #554

Convert `caffeine_assume` to be a proper external function

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

This commit introduces two methods to InterpreterContext which act as convenience methods for creating allocations. They mostly just forward to MemHeap::allocate but they also deal with some tricky bits around creating alloca allocations.
This was created since I needed them when converting some memory instruction implementations to use `InterpreterContext`.

Add some helpers for allocating memory to `InterpterContext`

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/InterpreterContext.cpp

Pretty much as in comment, this is just exposing an existing method that was already present on `MemHeapMgr` in a more convenient form.

Add helper method to get the allocation from a pointer

---

include/caffeine/Interpreter/ExternalFunction.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/CaffeineAssert.cpp
src/Interpreter/ExternalFuncs/CaffeineAssume.cpp
src/Interpreter/ExternalFuncs/MallocAlign.cpp

As in title, this means that we don't have to add a new header include to `CaffeineContext.cpp` every time we add a new external function. It also means that external functions can be entirely contained within their source files which is also nice.

Add builder functions for all external functions

---

include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/CaffeineSymbolicAlloca.cpp
src/Interpreter/Interpreter.cpp

As it turns out this was one of the more complicated functions to convert over to use `InterpeterContext` as it had a lot of assertions that needed to be convert into user-visible failures.
I've also continued along with putting builder functions for external functions within the `ExternalFunctions` class.
/stack #562

Convert `Interpreter::visitSymbolicAlloca` to an external function

---

include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/Interpreter/llvm.smul.with.overflow.cpp
src/Interpreter/Interpreter/llvm.umul.with.overflow.cpp

This PR is another fairly straightforward conversion. We've only implemented two intrinsics so I've gone and converted everything in one go.

Convert all implemented intrinsics to use `InterpreterContext`

---

include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/Calloc.cpp
src/Interpreter/Interpreter.cpp

As in title. This is another straightforward refactoring change.

Convert `visitCalloc` to be an external function

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/InterpreterContext.cpp

This PR adds two new methods to `InterpreterContext`:
- `mem_read`: read a `LLVMValue` instance from a resolved pointer
- `mem_write`: write a `LLVMValue` instance to a resolved pointer
Both of these are methods that I've extracted from my work on `setjmp`/`longjmp`.

Add helpers for reading/writing memory to `InterpreterContext`

---

include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/Interpreter.h
include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/ExternalFuncs/Free.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

As in title. This is another straightforward refactoring change. I've also added another helper function to `InterpreterContext` that simplifies some of the work around asserting that a pointer points to the start of an allocation.

Convert `visitFree` to be an external function

---

include/caffeine/IR/OperationBuilder.h
include/caffeine/Interpreter/InterpreterContext.h
src/IR/OperationBuilder.cpp
src/Interpreter/InterpreterContext.cpp

By giving the operation builder access to the current context we can provide a bunch of convenience methods that have needed to be implemented manually before this. This includes
- Constructors for creating operations that operate on `LLVMValue`s
- Constructors for creating operations that operate on `Pointer`s
Beyond that, it means that all constructions of `Operation` instances can (in the future) go through a single location. This isn't something I intend to go out an actively convert all expressions to, however, it will come into play once we want to take advantage of e-graphs.
Nevertheless, I'm intending for this builder to be useful _now_ and I'm going to use it to some effect when integrating e-graphs into the codebase.

Implement an `OperationBuilder` and have `InterpreterBuilder` derive from it

---

BUILD
bazel/clang-format.bzl

This means that it is run automatically whenever unit tests are run which should (hopefully) be helpful.

Convert bazel `:check-format` target to be a test

---

include/caffeine/Interpreter/InterpreterContext.h
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

This one used `TransformBuilder` instead of directly using `ctx` so it got missed in the first pass. Otherwise it's another straightforward conversion. I've taken advantage of some methods within `OperationBuilder` so I've stacked this change on top of that one. In addition, I've also added one more utility method to `InterpreterContext`.
/stack #570

Convert `visitLoadInst` to use `InterpreterContext`

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/ExprEval.h
src/IR/OperationBuilder.cpp
src/Interpreter/Context.cpp
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp
test/unit/Interpreter/ExprEval.cpp

The main thrust of this PR is as in the title. However, there were also some other bits that I needed to do in order to make everything work:
- I've removed some APIs from `Context` that are incompatible with the new API for `ExprEvaluator`. Specifically, this means `Context::lookup` and `Context::lookup_const`. The only user of these APIs was `InterpreterContext` so I've just migrated that use to lookup variables within the context directly.
- There were some builder methods that I forgot to implement when writing `OperationBuilder`. These are now implemented.
- One test suite had to be modified to also construct an `InterpreterContext` instance with which to build the `ExprEvaluator`.

Convert `ExprEvaluator` to use `InterpreterContext` and `OperationBuilder`

---

bazel/bitcode.bzl

This allows tests that need custom command line arguments (e.g. coverage) to be defined. The new command line arguments are passed by adding an `args` parameter to the caffeine_bitcode_test macro call.

[bazel] Add args parameter to caffeine_bitcode_test

---

include/caffeine/Interpreter/InterpreterContext.h
include/caffeine/Interpreter/StackFrame.h
src/Interpreter/ExprEval.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp

In order to integrate e-graphs I will need to modify `IRStackFrame`. However, in order to do this I need to not have a bunch of random places modifying it at will. This PR refactors all but two of the uses to use a helper method within `InterpreterContext` so that when I change it I only have to modify two locations.

Refactor `IRStackFrame::variables` to be private

---

include/caffeine/IR/OperationSimplifier.h
src/IR/Operation.h
src/IR/OperationSimplifier.cpp

With the changes from #582 it's no longer necessary for `OperationSimplifier` to support both copies and moves. This PR converts it to only do moves and only take non-const `Operation` references.
/stack #582

Clean up `OperationSimplifier` 

---

include/caffeine/IR/OperationBase.h
src/IR/Operation.cpp

Right now, `Operation`'s move constructor is basically a copy constructor. This has the potential to hide a number of bugs in how `Operation` instances are used. Currently, there are no issues that this exposes but I'm including it as a safeguard for when I start mucking around in the `Operation` internals.
/stack #583

Clear `Operation` fields upon move-out

---

include/caffeine/IR/OperationBase.h
src/IR/Operation.cpp
src/IR/OperationBase.cpp

This PR introduces a new class hierarchy for storing the non-operand data of an `Operation`. It's not currently used anywhere but follow-on commits will use it as I convert more operation types to use `OperationData` to store non-operand data.
/stack #584

Introduce alternative data representation for operation data

---

include/caffeine/IR/Operation.inl
include/caffeine/IR/OperationBase.h
src/IR/Operation.cpp
src/IR/OperationBase.cpp
test/unit/IR/Operation.cpp

This is all the easy ones that don't have any operands. The conversion was fairly straightforward. The one exception is that I needed to fix up the comparison operator for `Operation` so that caching and hashmaps worked as expected.

Convert `Constant`, `ConstantInt`, `ConstantFloat`, and `FunctionObject` to use `OperationData`

---

cmake/CaffeineTestUtils.cmake
libraries/libcxx/CMakeLists.txt

Previously `libc` would not be linked to `c` files, only `c++` files.
This PR fixes that

Unbust `libc` linking

---

bazel/toolchain/bitcode.bzl
cmake/CaffeineTestUtils.cmake
cmake/LLVMIRUtils.cmake
libraries/libcxx/CMakeLists.txt
test/run-pass/strlen.c
third_party/musl/setup.bzl

This commit fixes the musl libc `strlen` implementation. The root cause
if that when `__GNUC__` is defined, the `strlen` implementation assumes
that it can read past the buffer by a bit. However, under caffeine's
memory model this is not true.
To prevent clang from defining the GNU C macro, we set
-fgnuc-version=0` as a flag to clang.
/stack #595

Fix `strlen` test

---

include/caffeine/Interpreter/ExternalFuncs/Abort.h
include/caffeine/Interpreter/ExternalFunction.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/Executor.cpp
src/Interpreter/ExternalFuncs/Abort.cpp
test/run-fail/abort.c

This PR implements the C `abort` method. It's used by c++ in `std::terminate`
/stack #600

Implement `abort`

---

include/caffeine/Interpreter/ExprEval.h
src/Interpreter/Executor.cpp
src/Interpreter/ExprEval.cpp
src/Interpreter/ExternalFuncs/LongJmp.cpp

While working on c++ support I ran into this issue. This adds the fix
/stack #600

Implement support for evaluating `GlobalAlias`'

---

src/Solver/Z3/Convert.cpp
test/regression/issue-592.pass.requires-sitofp.c

As in title. I'll add follow-up PRs to implement the remaining operation types.
Closes #592

Implement support for `SIToFp` operation within `Z3Solver`

---

WORKSPACE
bazel/bitcode.bzl
bazel/toolchain/bitcode.bzl
libraries/builtins/BUILD
test/run-pass/BUILD
third_party/libcxx/build.bzl
third_party/libcxx/setup.bzl
third_party/musl/setup.bzl

This PR adds `libcxx` support to Bazel. In order to get the compilation working, I had to set a bunch of flags:
* `__CLANG_MAX_ALIGN_T_DEFINED` because both `clang` and `libc` defined `max_align_t`, and defined them to be different. Maybe we should define `__DEFINED_max_align_t` instead to suppress libc's `max_align_t` depending on whether we're linking with `libcxx` though.
* Remove `-fgnuc-version=0`. Essentially this means that we compile headers as if we're using GNUC, and we compile the implementation as if we don't. This is because:
* We want header to have GNUC so that the musl `offsetof` uses the same implementation as `clang`. Otherwise a good chunk of the `libcxx` exception handling static assertions fail.
* However, we want the implementation not to use GNUC because then it …

Add `libcxx` support to Bazel build

---

src/Solver/Z3/Convert.cpp
test/regression/issue-609.pass.requires-fptosi.c
test/regression/issue-609.pass.requires-fptoui.c

As in title. The semantics aren't exactly consistent with those of LLVM IR (since these produce poison if the float cannot be converted) but they are close enough for some things to work.
Closes #609

Implement `FpToUI` and `FpToSI` within `Z3Solver`

---

bazel/bitcode.bzl

Bazel docs say to use template strings for the progress message. However, in practice this don't actually seem to be expanded by bazel. This change replaces the template string with an expanded one.

Fix progress message within BitcodeBinaryOpt step

---

third_party/boost/setup.bzl

As in title. This brings us up to boost 1.78.

Update rules_boost to the latest version

---

include/caffeine/Interpreter/ExternalFuncs/Abort.h
include/caffeine/Interpreter/ExternalFuncs/CaffeineAssert.h
include/caffeine/Interpreter/ExternalFuncs/CaffeineAssume.h
include/caffeine/Interpreter/ExternalFuncs/MallocAlign.h
include/caffeine/Interpreter/ExternalFunction.h
src/Interpreter/ExternalFuncs/Abort.cpp
src/Interpreter/ExternalFuncs/CaffeineAssert.cpp
src/Interpreter/ExternalFuncs/CaffeineAssume.cpp
src/Interpreter/ExternalFuncs/CaffeineBuiltinResolve.cpp
src/Interpreter/ExternalFuncs/CaffeineSymbolicAlloca.cpp
src/Interpreter/ExternalFuncs/Calloc.cpp
src/Interpreter/ExternalFuncs/Free.cpp
src/Interpreter/ExternalFuncs/LongJmp.cpp
src/Interpreter/ExternalFuncs/MallocAlign.cpp
src/Interpreter/ExternalFuncs/SetJmp.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/Intrinsics/llvm.smul.with.overflow.cpp
src/Interpreter/Intrinsics/llvm.umul.with.overflow.cpp

This commit adds a `llvm::CallBase` to the `call` method because the
`abs` intrinsic needs to inspect the return type. Currently it's not
possible to do this with the current `ExternalFunction` class.

Add `llvm::CallBase` to `ExternalFunction` class

---

third_party/BUILD
third_party/z3/BUILD
third_party/z3/setup.bzl

This PR updates Z3 to version 4.8.14 and swaps it to be built using the cmake build system.

Build Z3 via cmake within bazel

---

include/caffeine/Interpreter/ExternalFunction.h
src/IR/Operation.cpp
src/Interpreter/CaffeineContext.cpp
src/Interpreter/Intrinsics/llvm.abs.cpp
test/run-fail/abs/basic-abs.c
test/run-pass/abs/basic-abs.c

This PR fixes a bug in `ICmpOp` where a constructor assumed that the operands are interchangeable and also implements the `llvm.abs.*` intrinsic

Implement `llvm.abs.*` intrinsic and fix `ICmpOp`

---

src/Interpreter/ExternalFuncs/CaffeineBuiltinResolve.cpp
src/Solver/Z3/Convert.cpp
test/unit/Solver/Z3Solver.cpp

See the text of issue #629 for a more detailed explanation of the underlying bug. This fixes #629 by first converting the `APFloat` to an `APFloat` containing its bit-representation and then reusing the bitcast logic to convert that back to a floating-point `z3::expr`.

Fix conversion of `ConstantFloat` to `z3::expr`

---

src/IR/Operation.cpp
src/Interpreter/ExternalFuncs/CaffeineBuiltinResolve.cpp
src/Solver/Z3/Convert.cpp
test/regression/issue-618.pass.requires-fpext.c
test/regression/issue-619.pass.requires-fptrunc.c
test/unit/Solver/Z3Solver.cpp

As in title. I've added some test cases that are pretty basic but do fail without this change. Stacked on top of #630 since that issue fixes the underlying issue causing the newly-added tests to fail.
Closes #618
Closes #619 
Closes #605 
/stack #630

Implement `FpExt` and `FpTrunc` within `Z3Solver`

---

include/caffeine/Interpreter/Store.h
include/caffeine/Interpreter/Store/CountLimitedStore.h
include/caffeine/Interpreter/Store/TimeLimitedStore.h
include/caffeine/Interpreter/ThreadQueueStore.h
src/Interpreter/Store/CountLimitedStore.cpp
src/Interpreter/Store/ThreadQueueStore.cpp
src/Interpreter/Store/TimeLimitedStore.cpp
tools/caffeine/main.cpp

This PR adds two different execution context stores:
- one that only returns at most a certain number of contexts before shutting down
- one that only returns contexts for a certain amount of time before shutting down
It then adds command line options for enabling either or both of these solvers on top of the normal one.
Closes #628

Add time-limited and count-limited execution context stores

---

include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/ExternalFuncs/ChainCall.h
include/caffeine/Interpreter/Interpreter.h
libraries/libcxx/CMakeLists.txt
src/Interpreter/ContextBacktrace.cpp
src/Interpreter/ExternalFuncs/ChainCall.cpp
src/Interpreter/Interpreter.cpp
test/run-pass/cpp/global-ctors.cpp
third_party/libcxx/setup.bzl

This PR adds handling for `llvm.global_ctors` which is required for c++ support
Closes #631

Handle `llvm.global_ctors`

---

third_party/divine/CMakeLists.txt

This makes it difficult to use caffeine unless it's in a global location.

Don't force divine to be a shared library

---

include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

This is just a small cleanup before doing some larger-scale refactoring within `Operation`.

Move some methods defined in `Operation.inl` to `Operation.cpp`

---

include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/OperationBase.h
include/caffeine/IR/Symbol.h
src/IR/Symbol.cpp

We don't have enough copies of strings for this to even be remotely near worth it.
/stack #653

Replace all uses of `InternedString` with `std::string`

---

include/caffeine/IR/OperationBase.h
src/IR/OperationBase.cpp
src/IR/OperationData.cpp

As in title. This avoids having to implement these for every derived type while I'm converting them.
/stack #654

Allow `Operation::with_new_operands` and `Operation::operand_at` to work with `OperationData`

---

include/caffeine/IR/Operation.inl
src/IR/Operation.cpp

As in title. My ultimate goal with this patch series is to get all the operation classes using `OperationData`.
/stack #660

Convert `ConstantArray` to use `OperationData` internally

---

src/IR/Operation.cpp

As in title. It turns out that these conversions will always require defining overrides of `operand_at` and `with_new_operands` until I flip the default in `Operation`. This will be fixed once the conversion work is complete.
/stack #660

Convert `BinaryOp` to use `OperationData`

---

include/caffeine/IR/Operation.def
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/OperationBuilder.h
src/IR/Operation.cpp
src/IR/OperationBuilder.cpp
src/IR/OperationSimplifier.cpp
src/IR/Operations/ArrayBase.cpp
src/Interpreter/ExternalFuncs/CaffeineSymbolicAlloca.cpp

This one ended up being a bit more involved. In addition to directly converting `FixedArray` to use `OperationData`, it also ended up replacing every location in the code that actually used `PersistentArray`. This will likely result in some increase in memory usage but for now it should be a small issue.

Convert `FixedArray` to use `OperationData`

---

include/caffeine/IR/Operation.h
include/caffeine/IR/OperationBase.h
src/IR/Operation.cpp
src/IR/OperationBase.cpp
src/IR/OperationSimplifier.cpp

This PR completes the refactoring of the `Operation` internals. After this PR `Operation` only has two main fields
- an `OperationData` pointer that stores any non-operand data, and,
- a list of operands
I've also kept the type field but it will always be the same as the one stored within `OperationData`. This is mainly to avoid a pointer dereference since the type is used everywhere within caffeine.

Delete the internal variant within `Operation`

---

include/caffeine/ADT/UnionFind.h
test/unit/ADT/UnionFind.cpp
test/unit/BUILD
test/unit/CMakeLists.txt

Pretty much as in the title. This PR adds an implementation of a union-find datastructure as well as a test that exercises it. Currently, it is unused but I will be using it in follow-up PRs to actually add e-graphs to caffeine.

Add an implementation of a union-find datastructure

---

bazel/BUILD
bazel/warnings.bzl
tools/caffeine/BUILD
tools/guided-fuzzing/BUILD

I've recently noticed that warning flags were not being passed to bazel. This PR changes that so that the compiler is properly detected and warning flags are passed appropriately.

Make warning flags work within bazel

---

BUILD
test/unit/BUILD
third_party/divine/BUILD
tools/caffeine/BUILD
tools/caffeine/main.cpp
tools/guided-fuzzing/BUILD

This is a bit of an attempt to reduce some the build times for caffeine. Currently, in order to build caffeine we link in a large part of LLVM. This is slow so, naturally, we would like to avoid that.
This PR does the following:
- Remove divine as a dependency from caffeine. Last time I tried to do this we weren't sure whether it would still be needed so I haven't actually gone and deleted it from the repo just yet. However, it is now dead code.
- Remove dependencies on llvm components that aren't actually needed within the `//:caffeine` target.
- The same goes for all the tools targets as well.
- Re-add all the dependencies that weren't required for `//:caffeine` but were needed by downstream targets (e.g. `//test/unit`) as dependencies for the downstream targets.
The end result of this …

Clean up unused bazel dependencies

---

include/caffeine/Support/Hashing.h

All this PR does is add some utilities that can be used to define an implementation of `std::hash` that wraps an existing `llvm::hash_value` implementation.
/stack #672

Add utilities for interfacing std::hash and llvm hashing

---

.github/workflows/bazel.yml
bazel/ci.bazelrc

Clang tends to give better error messages than gcc. Beyond that, we want to support both so we should really be testing with all compilers we support.

Also build with clang in bazel CI

---

bazel/warnings.bzl

There's a couple of unused arguments in dependencies. GCC doesn't seem to have a way to silence warnings for dependency headers so I've just gone and disabled the warning instead.

Silence unused parameter warnings under GCC

---

include/caffeine/IR/Operation.def
include/caffeine/IR/Operation.h
include/caffeine/IR/Operation.inl
include/caffeine/IR/OperationData.h
src/IR/OperationData.cpp
src/IR/Operations/EGraphNode.cpp
src/Solver/ModelEval.cpp
src/Solver/Z3/Convert.cpp

This PR adds a new operation type that just refers to an e-class id within the e-graph. It will be used by the e-graph class introduced in future PRs.
/stack #673

Add a new `Operation` to represent an e-graph node

---

include/caffeine/IR/OperationBase.h
src/IR/OperationBase.cpp

The egraph implementation will be using `OperationData` as part of its internal representation of operations. However, in order to make that work it needs to be able to access the data pointer of the operation. This PR adds a read-only accessor for `Operation::data_` as well as some constructors to create an operation from its data pointer + a list of operands.
/stack #674

Expose `Operation::data_` via a public accessor

---

.github/workflows/bazel.yml

As in title. Noticed that these the same across multiple runs which seems to result in problems.

Include compiler within the name of the CI artifact

---

.github/workflows/bazel.yml

We have a separate build to check formatting so running it as part of the regular test jobs just makes interpreting the results more confusing.

Avoid running format check for regular CI

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp

While writing further PRs I've come up with a couple of use cases where being able to reuse the caches needed to extract egraph expressions would be useful. This PR converts the `EGraphExtractor` class to one that can be used outside of `EGraph`.

Convert EGraphExtractor into a class that can be used externally

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp
src/IR/EGraphConstprop.cpp
test/unit/IR/EGraph.cpp

This PR implements incomplete constant propagation within E-Graphs, This is a big step towards making the e-graph actually have feature parity with our existing expression representation.
/stack #686

Implement basic constant propagation with E-Graphs

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp

Repeatedly rebuilding minimal-cost expressions that represent a given e-graph node every time we do an assertion is actually rather expensive. By caching both the expression and minimal cost for each e-graph node we can drastically reduce the cost of building expressions anew. The only issue is that, as e-classes are merged, the cached expressions may no longer be optimal. I've addressed this by invalidating the caches of all affected parents during egraph rebuild.
/stack #681

Automatically cache expressions for egraph e-classes

---

libraries/builtins/BUILD

Previously these weren't being optimized at all, which was resulting in some rather slow code. This isn't what we want so having it be optimized should help speed things up somewhat.

Optimize builtins with `-O3`

---

test/regression/issue-489.fail.write-to-const-global.c

It seems that this issue had already been fixed by some previous commit. This PR just adds the test case from the issue as a regression test.
Closes #489

Add regression test for issue #489

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp
test/unit/IR/EGraph.cpp

This PR extracts a couple of utility methods for `EGraph` that were introduced in #689. That PR is rather large so I've extracted these so that they can be reviewed more easily.
Here's a detailed summary of what was added:
- An `EGraph::extract` overload that takes an `Operation` instance and extracts it without requiring all intermediate expressions to be in the egraph.
- A similar overload for `EGraphExtractor::extract`
- An accessor for the opcode of an `ENode`.
- I have also deleted `EGraph::bulk_extract` since it was superseded by `EGraphExtractor`.

Extract EGraph utility methods from the EGraph integration PR

---

test/regression/issue-489.fail.write-to-const-global.c
test/run-fail/BUILD
test/tests.bzl

Having to run them in an unoptimized mode makes for really slow tests due to all the load and store queries that must be made to the solver. This resolves the issue by ensuring that they're compiled in the same way they were in the cmake build system.

Compile bitcode tests with `-O3`

---

include/caffeine/Model/GraphAssertionList.h
src/Model/GraphAssertionList.cpp
test/unit/Model/GraphAssertionList.cpp

Pretty much as in title. This will replace the `AssertionList` within `Context` and then we'll instead build the appropriate expressions right before sending them off to the solver.

Implement an AssertionList that uses eclass IDs

---

WORKSPACE
third_party/rules_pkg.diff

As in title. They don't seem to be handling an error correctly so all this does is patch the install script to do so.

Patch rules_pkg to not fail when reinstalling over an existing install

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp
test/unit/IR/EGraph.cpp

As in the title. We can avoid creating a temporary e-class in this case since the new e-node will be automatically merged with the existing one. This will help save some amount of memory in these cases.

Add more efficient combined add + merge operation to `EGraph`

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp

In order to save on memory for constant e-classes we delete all other e-nodes within the class. However, this has the side effect that indexes to existing e-nodes are invalidated. This isn't a problem for the current codebase, the future implementation of e-matching relies on this for rewrites to actually work so it needs to be changed. To make it work, we maintain all the e-nodes within the e-class until `EGraph::rebuild` is called at which point we can then clean everything up.
/stack #699

Delay unparenting constant e-classes until the e-graph is rebuilt

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatching.cpp

None of the types that could potentially use this have been added yet. However, this class was at the bottom of the hierarchy when I'm trying to split up the PR so it gets to be introduced first.  In short, this is just an interface with some extra bits so that it remains comparable and hashable (since that will matter in the coming PRs).
/stack #700

Add a filter interface for subclauses within an e-matching expression

---

include/caffeine/IR/EGraphMatching.h
include/caffeine/IR/EMatching/Filters.h
src/IR/EGraphMatching.cpp
src/IR/EMatching/Filters.cpp

This PR adds two implementations of `SubClauseFilter`:
- `IdenticalOperandsFilter`: Checks whether all the operands of the `ENode` refer to the same `E-Class`
- `ConstantOperandFilter`: Checks whether the integer value of the `ENode` is equivalent to the sign-extended value of a given constant.
Again, these aren't used anywhere yet but will be used in future PRs.
/stack #701

Add some `SubClauseFilter` implementations

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatching.cpp
src/IR/EMatching/Filters.cpp

This PR introduces the `Clause` and `SubClause` types which are used to match against e-classes in the graph.
The `SubClause` type matches against an individual e-node. It can include an opcode requirement, as well as refer to other subclauses that need to match on the operands of the e-node in order for the current subclause to match. For more custom filters, it can optionally include a `SubClauseFilter` instance (added in #701) which can do custom filtering beyond that.
The `Clause` type is then a top-level matching item that will correspond to a rewrite rule. It contains the actual rewrite function (`update`), a reference to the top-level subclause that it matches against, and, optionally, a global filter that can check for non-local requirements.
In the next PR, I'll introduce the …

Introduce matcher `Clause` and `SubClause` types

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatching.cpp

This PR introduces the `EMatcher` class. It is responsible for holding all the match clauses (i.e. queries) and rewrite rules that will be used to simplify the e-graph.
In the next PR I'll introduce the code to actually go and apply all the rewrite rules.
/stack #703

Add e-matcher clause storage class

---

include/caffeine/IR/EGraph.h
include/caffeine/IR/EGraphMatching.h
src/IR/EGraph.cpp
src/IR/EGraphMatching.cpp

This PR introduces the `GraphAccessor` class. All it does is prevent merges from happening while the rewrite rules are being applied, while recording which ones should happen so that they can all be done at once after the rewrites have occurred. See the comment on the class for more details.
/stack #704

Add an e-graph accessor class for use in rewrite rules

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp

This is needed to efficiently do updates when performing simplifications.
/stack #705

Track which e-classes have been updated within EGraph

---

include/caffeine/IR/EGraph.h
include/caffeine/IR/EGraphMatching.h
src/IR/EGraph.cpp
src/IR/EGraphMatcher.cpp

This commit is the main algorithmic part of the whole work on e-graphs and e-matching. It implements the logic for efficiently finding all queries that match within the `EMatcher` and then, for each matching query, it will apply the corresponding rewrite rule.
The algorithm implemented here is based off of the `equality_saturation` algorithm from within the [egg paper](https://arxiv.org/pdf/2004.03082.pdf). However, the details of the algorithm as implemented here end up spanning about 150 LOC. Check out `EGraphMatcher::equality_saturation` for the high level bits of code involved, and then look at the individual methods for the details of how each step is actually done.
/stack #706

Add implementation of e-matching and equality saturation

---

include/caffeine/Interpreter/CaffeineContext.h
include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/InterpreterContext.h
include/caffeine/Interpreter/TypeidDb.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/InterpreterContext.cpp
src/Interpreter/Intrinsics/llvm.eh.typeid.for.cpp
src/Interpreter/TypeidDb.cpp
test/run-pass/intrin/typeid_for/BUILD
test/run-pass/intrin/typeid_for/typeid-for.ll

This instrinsic is needed to get the selector values for c++
std::type_infos

Implement `llvm.eh.typeid.for` intrinsic

---

BUILD
cmake/CaffeineBazelConfig.cmake.in

When trying to use the install from the bazel build from within cmake I discovered that there were a few issues:
- The binaries did not have executable permissions
- The x86-linux-gllvm triplet was missing the cmake extension so vcpkg was unable to find it.
- It was very difficult to figure out how to use opt with caffeine in a way that works.
- The exported cmake targets were missing info on where to actually find the binaries in the install directory. This meant that generator rules such as `$<TARGET_FILE:caffeine::caffeine>` would not work.
This commit addresses all three:
- I've specified that the binaries should be executable
- I've fixed the rename rule for the triplet file
- I've exported our copy of opt as caffeine-opt so that it can just be used directly instead of futzing around …

Ensure that the install from the bazel build is usable

---

include/caffeine/IR/EGraph.h
src/IR/EGraph.cpp

This adds two methods to `EGraph`: `DebugPrint` and `DebugString`. These pretty much do exactly as expected.

Implement debug formatting for EGraph

---

include/caffeine/IR/EGraph.h
include/caffeine/IR/EGraphMatching.h
src/IR/EGraph.cpp
src/IR/EGraphConstprop.cpp
src/IR/EGraphMatcher.cpp
src/IR/EGraphMatching.cpp

This PR is a series of small fixes to various bits of code involved in the e-graph and e-matching. They have been extracted from the next set of changes that will introduce rewrites and start using them before making calls to the solver.
/stack #710

Batched small fixes to `EGraph` in order to make it work

---

include/caffeine/IR/EGraph.h
include/caffeine/IR/EGraphMatching.h
src/IR/EGraph.cpp
src/IR/EGraphMatching.cpp
src/IR/EMatching/Rewrites/Associativity.cpp
test/unit/IR/EMatching.cpp

As in title. The evaluation metric uses cached costs to select the expression to canonicalize so I've also gone and exposed a method on `EGraphEvaluator` that updates the cached costs.
/stack #715

Implement a rewrite rule that implements associativity rules

---

src/Solver/Z3Solver.cpp
src/Solver/Z3Solver.h

By default, Z3 will intercept a SIGINT signal that occurs within a solver call, swallow it, and return UNKNOWN from the solver. This doesn't at all match with what we want to do on a SIGINT call.
By looking at the Z3 source code, you can see an option "ctrl_c" that supposedly controls whether Z3 will catch SIGINT or not. The previous effort to fix this set the "ctrl_c" parameter on the Z3 context. What the Z3 API does not tell you is that "ctrl_c" is not a valid paramter on the Z3 context and that if you try to set "ctrl_c" on a Z3 context then it will just silently fail to do anything. This obviously meant that the previous attempt at fixing this (by me) did not do anything.
In this attempt, I traced the uses of the "ctrl_c" parameter within the Z3 codebase back to the public API that …

Prevent Z3 from intercepting SIGINT within solver calls

---

include/caffeine/Interpreter/CaffeineContext.h
src/IR/Symbol.cpp
src/Interpreter/CaffeineContext.cpp
src/Interpreter/Context.cpp
src/Interpreter/InterpreterContext.cpp
test/unit/IR/EMatching.cpp

This PR does the final bit of actually applying all the rewrites within caffeine:
- It adds an instance of `EMatcher` to `CaffeineContext` and sets it up with all the default transforms.
- We now call `EGraph::simplify` before running the solver when it is called through `InterpreterContext`
There are also some bugfixes here:
- The associativity rewrite has been rewritten so that it no longer produces an exponential number of rewrites
- I've done some clean-ups so that e-matching always accesses the right e-node and e-class
/stack #696

Integrate e-matching rewrites within the interpreter

---

include/caffeine/IR/EGraphMatching.h
src/IR/EMatching/AllMatchers.cpp
src/IR/EMatching/Rewrites/ICmpElimination.cpp
test/unit/IR/EMatching.cpp

This PR implements a bunch of rewrites that take operations of the form `(icmp.xx ?x ?x)` and replace them with an equivalent constant value. I've also included a test case that verifies that things are working correctly.
/stack #708

Implement additional eliminations for `icmp` opcode variants

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatching.cpp

This PR adds a few extra utility methods to `EGraphAccessor`:
- `get_op` returns an `OpRef` for a given `EClass`
- `add` and `add_merge` overloads that take `OpRef`s instead of `ENode`s

Add some utility methods to `EGraphAccessor`

---

src/Interpreter/StackFrame.cpp

This PR implements the resume branch of the `set_result` method. There's no tests, but it seems to work in https://github.com/insufficiently-caffeinated/caffeine/pull/598

Implement resume semantics

---

src/Interpreter/TypeidDb.cpp

Stripping bitcasts makes sure we register the global object instead of
some bitcast

Fix TypeId lookup

---

include/caffeine/IR/EGraphMatching.h
src/IR/EMatching/AllMatchers.cpp
src/IR/EMatching/Rewrites/ZExtTruncElimination.cpp
test/unit/IR/EMatching.cpp

This PR implements a rewrite that converts a `(zext (trunc ?x))` into a single truncate or zext along with an and operation. This is one of the rewrites that is needed to eliminate loads and stores to arrays.
/stack #723

Implement a rewrite to eliminate `(zext (trunc x))` operations

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraph.cpp
src/IR/EMatching/AllMatchers.cpp
src/IR/EMatching/Rewrites/LoadElimination.cpp
src/IR/EMatching/Rewrites/SelectConstprop.cpp
test/unit/IR/EMatching.cpp

This PR adds the following rewrites along with test cases to cover them:
- `(load (store))` is replaced with a select operation that replaces the `store` operation
- `(select (i1 x) ...)` is replaced with the appropriate operand
This means that, in general, loads from arrays with lots of stores to them will result in much smaller expressions since stores with constant offsets can be elided easily.
/stack #720

Add rewrite rules needed to elide stores when possible

---

include/caffeine/IR/EGraphMatching.h

There's a formatting error that's causing CI to fail. This PR just fixes it.

Fix formatting error within EGraphMatching.h

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatching.cpp

As in title. This adds some utility functions so that users that aren't friends with `EMatcher` can get read-only access to the clauses and subclauses contained within the `EMatcher` instance.

Add accessors for clauses and subclauses to `EMatcher`

---

include/caffeine/ADT/FunctionView.h
include/caffeine/IR/EGraphMatching.h
test/unit/ADT/FunctionView.cpp

This commit introduces a new erased function type called `function_view`. It is meant to be somewhat similar to std::function with the main difference being that it doesn't actually take ownership over the function but instead serves a function reference.
The idea is based off of the std::function_ref proposal for C++ but the implementation, while somewhat inspired by a blog post I found on something very similar, is mainly my own.
The code in this commit should work equally well with function pointers as with arbitrary callable objects and the test cases included verify that everything works as expected here.

Add a non-owning erased function type

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatcher.cpp
src/IR/EGraphMatching.cpp
src/IR/EMatching/Rewrites/ZExtTruncElimination.cpp
test/unit/IR/EMatching.cpp

This PR introduces a system that allows update functions within the E-Matcher to easily access the e-nodes that are needed to implement the rewrite. In addition, the e-matching code will now automatically call update with every combination of the captured nodes.
The motivation behind this is that as the number of expressions that make up the rewrite rule selector increase, so too does the difficulty in adding them all up to get the required data. This means that it is really difficult to write rewrite rules that use even 3 layers of matching clauses. By centralizing the difficult parts within the e-matching algorithm it can be much easier to write all of the rewrite rules we need.
The main algorithm is contained within `all_matchers` and `all_matchers_impl` within the `EGraphMatcher` …

Implement a captures system for `EMatcher`

---

include/caffeine/IR/EGraphMatching.h
src/IR/EGraphMatcher.cpp
src/IR/EGraphMatching.cpp

This PR is an extension to #729 that extends the captures system to allow a clause to capture multiple values simultaneously. Immediately after implementing #729, I found a use case that still didn't work (rewriting `(shl (lshr ?x ?y) ?z)` where `?y` and `?z` are constants) so I've now gone and extended capturing to support that use case as well.
/stack #729

Allow captures within e-matching with multiple values

---

include/caffeine/IR/EGraphMatching.h
src/IR/EMatching/Rewrites/ShiftElimination.cpp
test/unit/IR/EMatching.cpp

This PR implements a rewrite that takes expressions of the form `(shl (lshr ?x ?y) ?z)` where `?y` and `?z` are constants and rewrites them to consist of a single, net, shift and a mask. This is needed in order to eliminate the shift + zext that happens during a roundtrip through memory.
/stack #730

Implement a shl-lshr elimination rewrite

---

include/caffeine/IR/EGraphMatching.h
src/IR/EMatching/AllMatchers.cpp
src/IR/EMatching/Rewrites/ZExtTruncElimination.cpp

This simplifies the expression into a single overall `trunc` or `zext` opcode.

Add a rewrite for `(trunc (zext ?x))` expressions

---

include/caffeine/Solver/EarlyExitSolver.h
src/Solver/EarlyExitSolver.cpp
src/Solver/Solver.cpp

This adds a solver that recognizes some fixed cases and bails out early when they're recognized. Those cases are:
- The extra assertion is the literal false -> just return UNSAT
- The extra assertion is the literal true and all other assertions within the path condition are known to be satisfiable -> return SAT if this is a `check` call.
These checks are cheap to make and can potentially save a lot of time so doing them is definitely worthwhile.

Add a solver which exits early in some common cases

---

src/IR/EMatching/Rewrites/ICmpElimination.cpp

This is another independent rewrite similar to #734. All of these are patterns I've seen while trying to optimize the runtime for fuzzing zlib.
Note that this only works when `?x`, `?y` and `?z` are constant expressions.

Add a rewrite to eliminate `(icmp.eq (select ?a ?x ?y) ?z)` expressions

---

include/caffeine/ADT/ClonePointer.h
test/unit/ADT/ClonePointer.cpp

I found a couple of different issues with `clone_ptr` that hadn't been exercised by our codebase yet. This PR goes and fixes them. The specific issues I found were:
- `ClonePointer.h` has no `#pragma once` directive
- Copying a null `clone_ptr` results in a segfault
I've fixed both and added a test case verifying that the second bug is actually fixed.

Assorted bugfixes for `clone_ptr`

---

include/caffeine/Memory/MemHeap.h
include/caffeine/Memory/MemHeap.inl
include/caffeine/Memory/Pointer.h
src/Memory/MemHeap.cpp
src/Memory/Pointer.cpp

As in title. Note that I've left some methods still in `MemHeap.cpp` since they require either `MemHeap` or `MemHeapMgr` to implement.
/stack #738

Refactor `Pointer` out to its own header/cpp files

---

include/caffeine/Memory/BumpAllocator.h
include/caffeine/Memory/Heap.h
src/Memory/Heap.cpp

Strictly this is more-or-less a rewrite of `MemHeap` and `MemHeapMgr` to change two things:
- The internal concrete allocator now has a virtual interface instead of using a variant
- `allocate`, `deallocate`, and `resolve` now take an `InterpreterContext` instance
Since these changes break the interface I've created them in separate `Heap`/`MultiHeap`  classes which are currently unused. In a future PR I'll switch the rest of the codebase over to the new classes. Note that the implementation is mostly a copy-paste from `MemHeap` and `MemHeapMgr` with some small modifications to work with the two changes above.
/stack #739

Rethink `MemHeap` and `MemHeapMgr` to be more maintainable

---

include/caffeine/Memory/Allocation.h
include/caffeine/Memory/Heap.h
src/Memory/Allocation.cpp
src/Memory/Heap.cpp

This PR introduces a bunch of functions around reading and writing memory to `MultiHeap` along with corresponding overloads within `Allocation`. These were functions that I found I needed when trying to convert the rest of the codebase to use `MultiHeap` instead of `MemHeapMgr`.
/stack #740

Add additional utility functions to `MultiHeap`

---

.github/workflows/bazel.yml
bazel/ci.bazelrc

This PR makes a couple of changes to CI now that the bazel cache isn't working. As long as no targets are modified then the build should be pretty fast.

Modify cache options to avoid requiring a cache

---

.github/workflows/bazel.yml
BUILD
README.md
bazel/packaging.bzl

The caffeine install package includes a lot of headers by default. However, basically none of the external use-cases for caffeine need this so it doesn't really make sense to install them. This PR splits the `:install` target into `:install` and `:install-full` where the difference between the two is whether they also include the headers or not.
In addition, I've also included a fix to the header-packaging rule so that it correctly handles bazel rules with `include_prefix`

Avoid installing headers by default

---

include/caffeine/Interpreter/Executor.h
include/caffeine/Solver/InterruptSolver.h
include/caffeine/Solver/LoggingSolver.h
include/caffeine/Solver/SlicingSolver.h
include/caffeine/Solver/Solver.h
include/caffeine/Solver/Z3Solver.h
include/caffeine/Support/Signal.h
src/Interpreter/Executor.cpp
src/Solver/EarlyExitSolver.cpp
src/Solver/InterruptSolver.cpp
src/Solver/LoggingSolver.cpp
src/Solver/SlicingSolver.cpp
src/Solver/Solver.cpp
src/Solver/Z3Solver.cpp
src/Support/Signal.cpp
tools/caffeine/main.cpp

This PR implements graceful exit of caffeine if a user sends the SIGINT
signal. This is useful if we run with the `--coverage` flag because then
the line coverage will be dumped at the end of the run
Closes #637

Add graceful interrupt handling

---

.github/workflows/bazel.yml

As in the title. Turns out that we were copying the wrong artifact.

Fix error in CI due to copying the wrong artifact

---

.github/workflows/bazel.yml
bazel/ci.bazelrc

This reverts commit 47e9c03880b75d1eb83846e2e5dc7a9e203385dc since the cache server is now up and running.

Revert "Modify cache options to avoid requiring a cache (#744)"

---

include/caffeine/IR/OperationBuilder.h
include/caffeine/Interpreter/Context.h
include/caffeine/Interpreter/InterpreterContext.h
src/IR/OperationBuilder.cpp
src/Interpreter/Context.cpp
src/Interpreter/ExprEval.cpp
src/Interpreter/ExternalFuncs/CaffeineBuiltinResolve.cpp
src/Interpreter/ExternalFuncs/Free.cpp
src/Interpreter/ExternalFuncs/GenericUnwinding.cpp
src/Interpreter/ExternalFuncs/MallocAlign.cpp
src/Interpreter/ExternalFuncs/SetJmp.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/InterpreterContext.cpp
src/Solver/Solver.cpp
tools/caffeine/main.cpp

As in title. This changes everything to use `MultiHeap` which is cleaner and also has access to the `EGraph` when doing pointer resolutions.

Switch caffeine over to the new memory heap implementation

---

BUILD
include/caffeine/Interpreter/Store/LockfreeStore.h
src/Interpreter/Store/LockfreeStore.cpp

I'm still trying to get some last-minute optimizations in. Boost has a lockfree queue which should be a lot more efficient than our existing queue implementations. I've tested this in the complete set of commits I'll be putting up but I don't know how to test it on its own here.

Write a context store based on boost's `lockfree::queue`

---

include/caffeine/Interpreter/Store/ThreadCacheStore.h
src/Interpreter/Store/ThreadCacheStore.cpp

This is another context store that is meant to be combined with the one from #749. It caches one context per thread so that a thread that is currently running will rarely go idle.

Write a context store that caches one context per thread

---

.github/workflows/build-apt.yml
.github/workflows/find-coverage.yml
BUILD
CMakeLists.txt
WORKSPACE
cmake/FindLMDB.cmake
include/caffeine/Solver/CachingSolver.h
include/caffeine/Support/LMDB.h
src/CMakeLists.txt
src/Solver/CachingSolver.cpp
src/Support/LMDB.cpp
third_party/lmdb/lmdb.BUILD
third_party/lmdb/setup.bzl
tools/caffeine/main.cpp

This is the simplest possible implementation of a caching solver built on top of LMDB. All it does is convert each expression in the solver to a string, sort them, and then use them as the cache key. LMDB isn't optimal for this since it has a compile-time upper bound on the length of a key but I've bumped that up somewhat so that it works okay enough for now.
In the future it would be better to use a kv-store that supports arbitrary-length keys but I haven't found a local one as-of yet. RocksDB would probably be a good option for this.

Implement a caching solver on top of LMDB

---

include/caffeine/Interpreter/ExternalFunction.h
include/caffeine/Interpreter/Interpreter.h
src/Interpreter/CaffeineContext.cpp
src/Interpreter/Interpreter.cpp
src/Interpreter/Intrinsics/llvm.memcpy.cpp
src/Interpreter/Intrinsics/llvm.memset.cpp
tools/opt-plugin/builtins/plugin.cpp

As in the title. The motivation behind this is that I'd like to use memcpy to implement another intrinsic and couldn't do that when it's implemented as an external pass.
This implementation passes all the same tests as the existing one. However, I wasn't able to delete the existing part of the pass since it is still used as part of the implementation of `memmove`.

Implement `llvm.memcpy` as a builtin within caffeine

---

src/Solver/CachingSolver.cpp
src/Support/LMDB.cpp
tools/caffeine/main.cpp

Turns there were some issues with how I was using LMDB:
- The max size of the database was limited to 10MB so it would crash once it filled up due to an unhandled exception, and
- It was storing the cache in a directory literally named `~/.cache/caffeine` instead of `.cache/caffeine` under the home dir.
I've gone and fixed both of these issues so it should hopefully be robust at this point.

Fix some bugs around using LMDB

---

bazel/bitcode.bzl

As in title. This is important for making them run faster.

Ensure that bench targets are built with -O3

---

src/Solver/CachingSolver.cpp
third_party/lmdb/lmdb.BUILD

I ran into an error and this PR fixes + avoids it showing up again in case of failures.

Reduce page size of LMDB database to prevent internal errors

---

bench/BUILD
bench/digitcount.c

As in the title. This demo compares a couple of different ways of counting the base 10 digits in an integer (from a blog post by Daniel Lemire) to a reference implementation to ensure that they are all equivalent for all inputs.
Note that this can't actually be run without #757 but that's not needed for CI so I haven't included it here.

Write a demo that counts the digits in an integer

---

include/caffeine/IR/EGraphMatching.h
src/IR/EMatching/AllMatchers.cpp
src/IR/EMatching/Rewrites/ShiftCombination.cpp

I noticed that the bitcount example would produce expressions that looked like `(lshr (lshr (lshr (lshr a (i32 1)) (i32 1)) (i32 1)) (i32 1))`. This is not optimal so I went and added a egraph reduction that would combine all the shifts.

Add EGraph rule to combine repeated shift operations

---

src/IR/EMatching/Rewrites/ShiftCombination.cpp

It turns out that the rewrite introduced in #768 was converting everything to `lshr` operations. This is obviously not correct and it was caught by CI after it merged (not sure why it wasn't caught before). This PR fixes that by generating expressions with the correct opcode.

Fix bad shift combination test case

---

.github/workflows/bazel.yml
bazel/ci.bazelrc

Now that the cache server is no longer running, CI needs to be updated to instead use the cache from github actions.

Update CI to no longer use a cache server
